CREATE TABLE FRW_PATCH_HISTORY
(
    PATCH_ID             INTEGER NOT NULL,
    PATCH_DATE           CHAR(19) NOT NULL,
    VERSION              TEXT NOT NULL,
    LAST_PATCH_POINT     INTEGER,
    PATCH_FILE           TEXT NOT NULL,
    
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL    
);


CREATE TABLE FRW_BAL_ITEM
(
    BAL_ITEM_ID          INTEGER NOT NULL PRIMARY KEY,
    BAL_ITEM_CODE        TEXT NOT NULL UNIQUE,    
    BAL_ITEM_NAME        TEXT NOT NULL UNIQUE,    
    BAL_ITEM_TYPE        INTEGER,
    REF1                 INTEGER,
    REF2                 INTEGER,
    REF3                 INTEGER,
    ACTUAL_ID            INTEGER NOT NULL,

    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_BAL_ITEM_SEQ START 1;

CREATE TABLE FRW_BAL_OWNER
(
    BAL_OWNER_ID         INTEGER NOT NULL PRIMARY KEY,
    BAL_OWNER_CODE       TEXT NOT NULL UNIQUE,    
    BAL_OWNER_NAME       TEXT NOT NULL UNIQUE,    
    BAL_OWNER_TYPE       INTEGER,
    REF1                 INTEGER,
    REF2                 INTEGER,
    REF3                 INTEGER,
    ACTUAL_ID            INTEGER NOT NULL,

    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_BAL_OWNER_SEQ START 1;

CREATE TABLE FRW_BAL_DOCUMENT
(
    BAL_DOC_ID           INTEGER NOT NULL PRIMARY KEY,
    BAL_DOC_NO           TEXT NOT NULL UNIQUE, 
    BAL_DOC_DATE         CHAR(19) NOT NULL,
    BAL_DOC_NOTE         TEXT,       
    BAL_ITEM_TYPE        INTEGER NOT NULL,    
    BAL_OWNER_TYPE       INTEGER NOT NULL,
    BAL_DOC_TYPE         INTEGER NOT NULL,
    ACTUAL_ID            INTEGER NOT NULL,

    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_BAL_DOCUMENT_SEQ START 1;

CREATE TABLE FRW_BAL_DOCUMENT_DETAIL
(
    BAL_DOC_DTL_ID       INTEGER NOT NULL UNIQUE,
    BAL_DOC_ID           INTEGER NOT NULL,      
    BAL_ITEM_ID          INTEGER NOT NULL,    
    BAL_OWNER_ID         INTEGER NOT NULL,
    DIRECTION            CHAR(1) NOT NULL,
    ACTUAL_ID            INTEGER NOT NULL,
    
    BEGIN_QTY_AVG        NUMERIC(10, 4) NOT NULL,
    BEGIN_AMOUNT_AVG     NUMERIC(10, 4) NOT NULL,
    BEGIN_QTY_FIFO       NUMERIC(10, 4) NOT NULL,
    BEGIN_AMOUNT_FIFO    NUMERIC(10, 4) NOT NULL,

    TX_QTY_AVG           NUMERIC(10, 4) NOT NULL,
    TX_AMT_AVG           NUMERIC(10, 4) NOT NULL,
    TX_QTY_FIFO          NUMERIC(10, 4) NOT NULL,
    TX_AMT_FIFO          NUMERIC(10, 4) NOT NULL,
    
    END_QTY_AVG          NUMERIC(10, 4) NOT NULL,
    END_AMOUNT_AVG       NUMERIC(10, 4) NOT NULL,
    END_QTY_FIFO         NUMERIC(10, 4) NOT NULL,
    END_AMOUNT_FIFO      NUMERIC(10, 4) NOT NULL,

    LOT_NO               TEXT,
    LOT_DESC             TEXT,
    LOT_EXPIRE_DATE      CHAR(19),

    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL,

    FOREIGN KEY (BAL_DOC_ID) REFERENCES FRW_BAL_DOCUMENT(BAL_DOC_ID),
    FOREIGN KEY (BAL_ITEM_ID) REFERENCES FRW_BAL_ITEM(BAL_ITEM_ID),
    FOREIGN KEY (BAL_OWNER_ID) REFERENCES FRW_BAL_OWNER(BAL_OWNER_ID)            
);

CREATE SEQUENCE FRW_BAL_DOCUMENT_DETAIL_SEQ START 1;

CREATE TABLE FRW_BAL_ACCUMULATE
(
    BAL_ID               INTEGER NOT NULL PRIMARY KEY,
    BAL_DATE             CHAR(19) NOT NULL,      
    BAL_LEVEL            INTEGER NOT NULL,    
    BAL_ITEM_ID          INTEGER NOT NULL,
    BAL_OWNER_ID         INTEGER NOT NULL,

    BEGIN_QTY_AVG        NUMERIC(10, 4) NOT NULL,
    BEGIN_AMOUNT_AVG     NUMERIC(10, 4) NOT NULL,
    BEGIN_PRICE_AVG      NUMERIC(10, 4) NOT NULL,
    
    BEGIN_QTY_FIFO       NUMERIC(10, 4) NOT NULL,
    BEGIN_AMOUNT_FIFO    NUMERIC(10, 4) NOT NULL,
    BEGIN_PRICE_FIFO     NUMERIC(10, 4) NOT NULL,    

    IN_QTY_AVG           NUMERIC(10, 4) NOT NULL,
    IN_AMOUNT_AVG        NUMERIC(10, 4) NOT NULL,
    IN_PRICE_AVG         NUMERIC(10, 4) NOT NULL,  

    IN_QTY_FIFO          NUMERIC(10, 4) NOT NULL,
    IN_AMOUNT_FIFO       NUMERIC(10, 4) NOT NULL,
    IN_PRICE_FIFO        NUMERIC(10, 4) NOT NULL,  

    OUT_QTY_AVG          NUMERIC(10, 4) NOT NULL,
    OUT_AMOUNT_AVG       NUMERIC(10, 4) NOT NULL,
    OUT_PRICE_AVG        NUMERIC(10, 4) NOT NULL,  

    OUT_QTY_FIFO         NUMERIC(10, 4) NOT NULL,
    OUT_AMOUNT_FIFO      NUMERIC(10, 4) NOT NULL,
    OUT_PRICE_FIFO       NUMERIC(10, 4) NOT NULL,  

    END_QTY_AVG          NUMERIC(10, 4) NOT NULL,
    END_AMOUNT_AVG       NUMERIC(10, 4) NOT NULL,
    END_PRICE_AVG        NUMERIC(10, 4) NOT NULL,
    
    END_QTY_FIFO         NUMERIC(10, 4) NOT NULL,
    END_AMOUNT_FIFO      NUMERIC(10, 4) NOT NULL,
    END_PRICE_FIFO       NUMERIC(10, 4) NOT NULL, 

    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_BAL_ACCUMULATE_SEQ START 1;

CREATE TABLE FRW_BAL_LOT
(
    BAL_LOT_ID           INTEGER NOT NULL PRIMARY KEY,
    BAL_LOT_DATE         CHAR(19) NOT NULL,      
    BAL_LEVEL            INTEGER NOT NULL,    
    BAL_ITEM_ID          INTEGER NOT NULL,
    BAL_OWNER_ID         INTEGER NOT NULL,
    LOT_NO               TEXT NOT NULL,
    LOT_DESC             TEXT,
    LOT_EXPIRE_DATE      CHAR(19),
    QUANTITY             NUMERIC(10, 4) NOT NULL,
    AMOUNT               NUMERIC(10, 4) NOT NULL,
    PRICE                NUMERIC(10, 4) NOT NULL,
    ANNONYMOUS_FLAG      CHAR(1) NOT NULL,

    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL    
);

CREATE SEQUENCE FRW_BAL_LOT_SEQ START 1;

ALTER TABLE FRW_BAL_OWNER DROP CONSTRAINT FRW_BAL_OWNER_BAL_OWNER_NAME_KEY;
ALTER TABLE FRW_BAL_ITEM DROP CONSTRAINT FRW_BAL_ITEM_BAL_ITEM_NAME_KEY;

ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ADD COLUMN GROUP_ID INTEGER;

ALTER TABLE FRW_BAL_ITEM DROP CONSTRAINT FRW_BAL_ITEM_BAL_ITEM_CODE_KEY;
ALTER TABLE FRW_BAL_ITEM ADD CONSTRAINT FRW_BAL_ITEM_BAL_ITEM_CODE_KEY UNIQUE (BAL_ITEM_CODE, BAL_ITEM_TYPE);

ALTER TABLE FRW_BAL_OWNER DROP CONSTRAINT FRW_BAL_OWNER_BAL_OWNER_CODE_KEY;
ALTER TABLE FRW_BAL_OWNER ADD CONSTRAINT FRW_BAL_OWNER_BAL_OWNER_CODE_KEY UNIQUE (BAL_OWNER_CODE, BAL_OWNER_TYPE);

ALTER TABLE FRW_BAL_DOCUMENT DROP CONSTRAINT FRW_BAL_DOCUMENT_BAL_DOC_NO_KEY;

CREATE TABLE FRW_TEST1
(
    BAL_ID INTEGER NOT NULL PRIMARY KEY
);

DROP TABLE FRW_TEST1;

CREATE TABLE FRW_DOCUMENT_NUMBER
(
    DOCUMENT_NUMBER_ID        INTEGER NOT NULL PRIMARY KEY,
    DOC_TYPE                  TEXT NOT NULL UNIQUE,
    LAST_RUN_YEAR             INTEGER NOT NULL,
	LAST_RUN_MONTH            INTEGER NOT NULL,
	PREFIX                    TEXT,
	FORMULA                   TEXT NOT NULL,
	RESET_CRITERIA            INTEGER NOT NULL,
	CURRENT_SEQ               INTEGER NOT NULL,
	START_SEQ                 INTEGER NOT NULL,
	SEQ_LENGTH                INTEGER NOT NULL,
	YEAR_OFFSET               INTEGER NOT NULL,
	PARENT_ID                 INTEGER NOT NULL,
	GROUP_ID                  INTEGER NOT NULL,

    CREATE_DATE               CHAR(19) NOT NULL,
    MODIFY_DATE               CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_DOCUMENT_NUMBER_SEQ START 1;

CREATE TABLE FRW_PATCH_POST
(
    PATCH_POST_ID             INTEGER NOT NULL PRIMARY KEY,
	PATCH_DATE                CHAR(19) NOT NULL,
	FUNCTION_NAME             TEXT NOT NULL,
	FILE_NAME                 TEXT NOT NULL,

    CREATE_DATE               CHAR(19) NOT NULL,
    MODIFY_DATE               CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_PATCH_POST_SEQ START 1;


CREATE TABLE FRW_USER_GROUP
(
    GROUP_ID                  INTEGER NOT NULL PRIMARY KEY,
	GROUP_NAME                TEXT NOT NULL UNIQUE,
	DESCRIPTION               TEXT NOT NULL,

    CREATE_DATE               CHAR(19) NOT NULL,
    MODIFY_DATE               CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_USER_GROUP_SEQ START 1;

CREATE TABLE FRW_USER
(
    USER_ID                  INTEGER NOT NULL PRIMARY KEY,
	USER_NAME                TEXT NOT NULL UNIQUE,
	DESCRIPTION              TEXT,
	PASSWORD                 TEXT NOT NULL,
    EMAIL                    TEXT,
	IS_ENABLE                CHAR(1) NOT NULL,
	IS_ADMIN                 CHAR(1) NOT NULL,
    IS_INTIAL                CHAR(1) NOT NULL,
    GROUP_ID                 INTEGER NOT NULL,

    CREATE_DATE              CHAR(19) NOT NULL,
    MODIFY_DATE              CHAR(19) NOT NULL,

    FOREIGN KEY (GROUP_ID) REFERENCES FRW_USER_GROUP(GROUP_ID)
);

CREATE SEQUENCE FRW_USER_SEQ START 1;

CREATE TABLE FRW_LOGIN_HISTORY
(
    LOGIN_ID                  INTEGER NOT NULL PRIMARY KEY,
	LOGIN_DATE                CHAR(19) NOT NULL,
    LOGOUT_DATE               CHAR(19),
	IP_ADDRESS                TEXT,
	USER_NAME                 TEXT,
    FAILED_PASSWORD           TEXT,
	LOGIN_SUCCESS             CHAR(1) NOT NULL,
    ERROR_DESC                TEXT,
    SESSION                   TEXT,

    CREATE_DATE               CHAR(19) NOT NULL,
    MODIFY_DATE               CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_LOGIN_HISTORY_SEQ START 1;

CREATE TABLE FRW_USER_VARIABLE
(
    VARIABLE_ID                INTEGER NOT NULL PRIMARY KEY,
	USER_ID                    INTEGER NOT NULL,    
	VARIABLE_NAME              TEXT NOT NULL,
    VARIABLE_VALUE             TEXT,

    CREATE_DATE               CHAR(19) NOT NULL,
    MODIFY_DATE               CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_USER_VARIABLE_SEQ START 1;

ALTER TABLE FRW_USER ALTER COLUMN GROUP_ID DROP NOT NULL;

ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN BEGIN_QTY_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN BEGIN_AMOUNT_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN BEGIN_PRICE_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN BEGIN_QTY_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN BEGIN_AMOUNT_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN BEGIN_PRICE_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN IN_QTY_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN IN_AMOUNT_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN IN_PRICE_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN IN_QTY_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN IN_AMOUNT_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN IN_PRICE_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN OUT_QTY_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN OUT_AMOUNT_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN OUT_PRICE_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN OUT_QTY_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN OUT_AMOUNT_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN OUT_PRICE_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN END_QTY_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN END_AMOUNT_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN END_PRICE_AVG TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN END_QTY_FIFO TYPE NUMERIC(13, 4);
ALTER TABLE FRW_BAL_ACCUMULATE ALTER COLUMN END_AMOUNT_FIFO TYPE NUMERIC(13, 4);

ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN BEGIN_QTY_AVG TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN BEGIN_AMOUNT_AVG TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN BEGIN_QTY_FIFO TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN BEGIN_AMOUNT_FIFO TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN TX_QTY_AVG TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN TX_AMT_AVG TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN TX_QTY_FIFO TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN TX_AMT_FIFO TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN END_QTY_AVG TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN END_AMOUNT_AVG TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN END_QTY_FIFO TYPE NUMERIC(14, 4);
ALTER TABLE FRW_BAL_DOCUMENT_DETAIL ALTER COLUMN END_AMOUNT_FIFO TYPE NUMERIC(14, 4);

ALTER TABLE FRW_BAL_DOCUMENT ADD ACTUAL_DOC_DATE CHAR(19);
UPDATE FRW_BAL_DOCUMENT SET ACTUAL_DOC_DATE = BAL_DOC_DATE;

ALTER TABLE FRW_DOCUMENT_NUMBER ADD CUSTOM_SEQ_VAR TEXT;
UPDATE FRW_DOCUMENT_NUMBER SET CUSTOM_SEQ_VAR = '${ud_2m2y}';

ALTER TABLE FRW_DOCUMENT_NUMBER ADD USE_CUSTOM_SEQ CHAR(1);
UPDATE FRW_DOCUMENT_NUMBER SET USE_CUSTOM_SEQ = 'N';

ALTER TABLE FRW_DOCUMENT_NUMBER ADD SEQUENCE_DEFINITION TEXT;

UPDATE FRW_DOCUMENT_NUMBER SET CUSTOM_SEQ_VAR = '${ud_4y-2m}';


CREATE TABLE FRW_ACCESS_RIGHT
(
    ACCESS_RIGHT_ID                 INTEGER NOT NULL PRIMARY KEY,
    ACCESS_RIGHT_CODE               TEXT NOT NULL UNIQUE,
    RIGHT_DESCRIPTION               TEXT,
    ACCESS_CATEGORY                 TEXT NOT NULL,
    ACCESS_NS                       TEXT NOT NULL,

    CREATE_DATE                     CHAR(19) NOT NULL,
    MODIFY_DATE                     CHAR(19) NOT NULL
);

CREATE SEQUENCE FRW_ACCESS_RIGHT_SEQ START 1;

CREATE TABLE FRW_GROUP_PERMISSION
(
    GROUP_PERMISSION_ID            INTEGER NOT NULL PRIMARY KEY,
    GROUP_ID                       INTEGER NOT NULL,
    ACCESS_RIGHT_ID                INTEGER NOT NULL,
    IS_ENABLE                      CHAR(1) NOT NULL,
    
    CREATE_DATE                    CHAR(19) NOT NULL,
    MODIFY_DATE                    CHAR(19) NOT NULL,
    
    FOREIGN KEY(GROUP_ID) REFERENCES FRW_USER_GROUP(GROUP_ID),
    FOREIGN KEY(ACCESS_RIGHT_ID) REFERENCES FRW_ACCESS_RIGHT(ACCESS_RIGHT_ID)
);

CREATE SEQUENCE FRW_GROUP_PERMISSION_SEQ START 1;

ALTER TABLE FRW_ACCESS_RIGHT ADD DEFAULT_VALUE CHAR(1);
