<?php
/*
Purpose : Model for ACCOUNT_DOC
Created By : Seubpong Monsar
Created Date : 09/04/2017 (MM/DD/YYYY)
IBSVer : 1.0
*/

declare(strict_types=1);

require_once "phar://onix_erp_framework.phar/onix_erp_include.php";

class MAccountDoc extends MBaseModel
{
    private $cols = array(

        [ # 0 For insert, update, delete
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'DOCUMENT_DATE:S:DOCUMENT_DATE:N',
            'DUE_DATE:S:DUE_DATE:N',
            'DOCUMENT_NO:S:DOCUMENT_NO:Y',
            'DOCUMENT_DESC:S:DOCUMENT_DESC:N',
            'ENTITY_ID:REFID:ENTITY_ID:Y',
            'LOCATION_ID:REFID:LOCATION_ID:Y',
            'BRANCH_ID:REFID:BRANCH_ID:Y',
            'ACCOUNT_SIDE:NZ:ACCOUNT_SIDE:N',
            'DOCUMENT_TYPE:NZ:DOCUMENT_TYPE:N',
            'DOCUMENT_STATUS:NZ:DOCUMENT_STATUS:N',
            'FINAL_DISCOUNT_AMT:NZ:FINAL_DISCOUNT_AMT:N',
            'ITEM_DISCOUNT_AMT:NZ:ITEM_DISCOUNT_AMT:N',
            'VAT_PCT:NZ:VAT_PCT:N',
            'VAT_AMT:NZ:VAT_AMT:N',
            'WH_TAX_AMT:NZ:WH_TAX_AMT:N',
            'WH_TAX_PCT:NZ:WH_TAX_PCT:N',
            'PAYMENT_TYPE:NZ:PAYMENT_TYPE:N',
            'INVENTORY_DOC_ID:REFID:INVENTORY_DOC_ID:Y',
            'CASH_DOC_ID:REFID:CASH_DOC_ID:Y',
            'AR_TX_TYPE:S:AR_TX_TYPE:N',
            'AR_TX_AMOUNT:NZ:AR_TX_AMOUNT:N',
            'AR_BEGIN_AMOUNT:NZ:AR_BEGIN_AMOUNT:N',
            'AR_END_AMOUNT:NZ:AR_END_AMOUNT:N',
            'CASH_ACCOUNT_ID:REFID:CASH_ACCOUNT_ID:Y',
            'FINAL_DISCOUNT:S:FINAL_DISCOUNT:N',
            'EMPLOYEE_ID:REFID:EMPLOYEE_ID:Y',
            'BILL_SIMULATE_ID:REFID:BILL_SIMULATE_ID:N',
            'PROMOTION_TOTAL_AMOUNT:NZ:PROMOTION_TOTAL_AMOUNT:N',
            'PROMOTION_AMOUNT:NZ:PROMOTION_AMOUNT:N',
            'PROMOTION_FINAL_DISCOUNT_AMOUNT:NZ:PROMOTION_FINAL_DISCOUNT_AMOUNT:N',
            'PROMO_FREE_COUNT:NZ:PROMO_FREE_COUNT:N',
            'PROMO_VOUCHER_COUNT:NZ:PROMO_VOUCHER_COUNT:N',
            'PROMO_POSTFREE_COUNT:NZ:PROMO_POSTFREE_COUNT:N',
            'REVENUE_EXPENSE_AMT:NZ:REVENUE_EXPENSE_AMT:N',
            'REVENUE_EXPENSE_FOR_WH_AMT:NZ:REVENUE_EXPENSE_FOR_WH_AMT:N',
            'REVENUE_EXPENSE_FOR_VAT_AMT:NZ:REVENUE_EXPENSE_FOR_VAT_AMT:N',
            'AR_AP_AMT:NZ:AR_AP_AMT:N',
            'VAT_TYPE:NZ:VAT_TYPE:N',
            'ALLOW_AR_AP_NEGATIVE:S:ALLOW_AR_AP_NEGATIVE:Y',
            'ALLOW_CASH_NEGATIVE:S:ALLOW_CASH_NEGATIVE:Y',
            'ALLOW_INVENTORY_NEGATIVE:S:ALLOW_INVENTORY_NEGATIVE:Y',
            'APPROVED_DATE:S:APPROVED_DATE:N',
            'APPROVED_SEQ:NZ:APPROVED_SEQ:N',
            'PRICING_AMT:NZ:PRICING_AMT:N',
            'CASH_ACTUAL_RECEIPT_AMT:NZ:CASH_ACTUAL_RECEIPT_AMT:N',
            'CASH_RECEIPT_AMT:NZ:CASH_RECEIPT_AMT:N',
            'PRIMARY_REVENUE_EXPENSE_AMT:NZ:PRIMARY_REVENUE_EXPENSE_AMT:N',
            'PRIMARY_ITEM_DISCOUNT_AMT:NZ:PRIMARY_ITEM_DISCOUNT_AMT:N',
            'PRIMARY_FINAL_DISCOUNT_AVG_AMT:NZ:PRIMARY_FINAL_DISCOUNT_AVG_AMT:N',
            'RECEIPT_FLAG:S:RECEIPT_FLAG:Y',
            'REF_DOCUMENT_NO:S:REF_DOCUMENT_NO:Y',
            'ENTITY_ADDRESS_ID:REFID:ENTITY_ADDRESS_ID:N',            
            'RECEIPT_PAID_AMT:NZ:RECEIPT_PAID_AMT:N',
            'RECEIPT_DEBT_AMT:NZ:RECEIPT_DEBT_AMT:N',
            'ARAP_REMAIN_AMT:NZ:ARAP_REMAIN_AMT:N',
            'ARAP_PAID_AMT:NZ:ARAP_PAID_AMT:N',
            'ARAP_PAID_OFF_FLAG:S:ARAP_PAID_OFF_FLAG:Y',
            'RECEIPT_ID:REFID:RECEIPT_ID:Y',
            'IS_PROMOTION_MODE:S:IS_PROMOTION_MODE:Y',
            'INDEX_DOC_INCLUDE:S:INDEX_DOC_INCLUDE:Y',
            'CHANGE_TYPE:NZ:CHANGE_TYPE:Y',
            'BY_VOID_FLAG:S:BY_VOID_FLAG:Y',
            'WH_DEFINITION:S:WH_DEFINITION:N',
            'PROJECT_ID:REFID:PROJECT_ID:Y',
            'ACTUAL_TX_DATE:S:ACTUAL_TX_DATE:N',
            'CASH_RECEIVE_AMT:NZ:CASH_RECEIVE_AMT:N',
            'CASH_CHANGE_AMT:NZ:CASH_CHANGE_AMT:N',
            'REF_WH_DOC_NO:S:REF_WH_DOC_NO:N',
            'REF_PO_NO:S:REF_PO_NO:Y',
            'REF_RECEIPT_NO:S:REF_RECEIPT_NO:N',
            'CHEQUE_ID:REFID:CHEQUE_ID:Y',
            'INVOICE_AVAILABLE_FLAG:S:INVOICE_AVAILABLE_FLAG:Y',
            'WH_PAY_TYPE:NZ:WH_PAY_TYPE:N',
            'REF_DOCUMENT_DATE:S:REF_DOCUMENT_DATE:Y',
            'REF_QUOTATION_NO:S:REF_QUOTATION_NO:Y',
            'VAT_MONTH_YEAR:S:VAT_MONTH_YEAR:Y',
            'WH_MONTH_YEAR:S:WH_MONTH_YEAR:Y',
            'INTERNAL_DRCR_FLAG:S:INTERNAL_DRCR_FLAG:Y',
            'REF_QUOTATION_ID:REFID:REF_QUOTATION_ID:Y',
            'REF_SALE_ORDER_ID:REFID:REF_SALE_ORDER_ID:Y',
            'REF_SALE_ORDER_NO:S:REF_SALE_ORDER_NO:Y',
            'SO_IN_USED_BY_INVOICE:S:SO_IN_USED_BY_INVOICE:Y',            
            'INDEX_PAYMENT:S:INDEX_PAYMENT:N',
            'IS_APPROVED_DOC_NO:S:IS_APPROVED_DOC_NO:N',
            'BILL_SUMMARY_ID:REFID:BILL_SUMMARY_ID:N',
            'INDEX_PROJECT:S:INDEX_PROJECT:N',
            'NOTE:S:NOTE:Y',
            'DOCUMENT_YYYYMM:S:DOCUMENT_YYYYMM:N',
            'DOCUMENT_YYYY:S:DOCUMENT_YYYY:N',
            'VAT_CLAIMABLE:S:VAT_CLAIMABLE:Y',
            'DRCR_FOR_EXPENSE_REVENUE:S:DRCR_FOR_EXPENSE_REVENUE:Y',
            'REDEEM_DOCUMENT_ID:REFID:REDEEM_DOCUMENT_ID:N',

            'CREATE_DATE:CD:CREATE_DATE:N',
            'MODIFY_DATE:MD:MODIFY_DATE:N',
        ],

        [ # 1 For Get account doc List
            'AD.ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'AD.DOCUMENT_DATE:S:DOCUMENT_DATE:N',
            'AD.DUE_DATE:S:DUE_DATE:N',
            'AD.DOCUMENT_NO:S:DOCUMENT_NO:Y',
            'AD.DOCUMENT_DESC:S:DOCUMENT_DESC:Y',
            'AD.ENTITY_ID:REFID:ENTITY_ID:Y',
            'AD.LOCATION_ID:REFID:LOCATION_ID:Y',
            'AD.BRANCH_ID:REFID:BRANCH_ID:Y',
            'AD.ACCOUNT_SIDE:NZ:ACCOUNT_SIDE:Y',
            'AD.DOCUMENT_TYPE:NZ:DOCUMENT_TYPE:Y',
            'AD.DOCUMENT_STATUS:NZ:DOCUMENT_STATUS:Y',
            'AD.FINAL_DISCOUNT_AMT:NZ:FINAL_DISCOUNT_AMT:N',
            'AD.ITEM_DISCOUNT_AMT:NZ:ITEM_DISCOUNT_AMT:N',
            'AD.VAT_PCT:NZ:VAT_PCT:N',
            'AD.VAT_AMT:NZ:VAT_AMT:N',
            'AD.WH_TAX_AMT:NZ:WH_TAX_AMT:N',
            'AD.WH_TAX_PCT:NZ:WH_TAX_PCT:N',
            'AD.PAYMENT_TYPE:NZ:PAYMENT_TYPE:Y',
            'AD.INVENTORY_DOC_ID:REFID:INVENTORY_DOC_ID:Y',
            'AD.CASH_DOC_ID:REFID:CASH_DOC_ID:Y',
            'AD.AR_TX_TYPE:S:AR_TX_TYPE:Y',
            'AD.AR_TX_AMOUNT:NZ:AR_TX_AMOUNT:N',
            'AD.AR_BEGIN_AMOUNT:NZ:AR_BEGIN_AMOUNT:N',
            'AD.AR_END_AMOUNT:NZ:AR_END_AMOUNT:N',
            'AD.CASH_ACCOUNT_ID:REFID:CASH_ACCOUNT_ID:Y',
            'AD.BILL_SIMULATE_ID:REFID:BILL_SIMULATE_ID:N',
            'AD.PROMOTION_TOTAL_AMOUNT:NZ:PROMOTION_TOTAL_AMOUNT:N',
            'AD.PROMOTION_AMOUNT:NZ:PROMOTION_AMOUNT:N',
            'AD.PROMOTION_FINAL_DISCOUNT_AMOUNT:NZ:PROMOTION_FINAL_DISCOUNT_AMOUNT:N',
            'AD.PROMO_FREE_COUNT:NZ:PROMO_FREE_COUNT:N',
            'AD.PROMO_VOUCHER_COUNT:NZ:PROMO_VOUCHER_COUNT:N',
            'AD.PROMO_POSTFREE_COUNT:NZ:PROMO_POSTFREE_COUNT:N',
            'AD.REVENUE_EXPENSE_AMT:NZ:REVENUE_EXPENSE_AMT:N',
            'AD.REVENUE_EXPENSE_FOR_WH_AMT:NZ:REVENUE_EXPENSE_FOR_WH_AMT:N',
            'AD.REVENUE_EXPENSE_FOR_VAT_AMT:NZ:REVENUE_EXPENSE_FOR_VAT_AMT:N',
            'AD.AR_AP_AMT:NZ:AR_AP_AMT:N',
            'AD.VAT_TYPE:NZ:VAT_TYPE:N',
            'AD.ALLOW_AR_AP_NEGATIVE:S:ALLOW_AR_AP_NEGATIVE:Y',
            'AD.ALLOW_CASH_NEGATIVE:S:ALLOW_CASH_NEGATIVE:Y',
            'AD.ALLOW_INVENTORY_NEGATIVE:S:ALLOW_INVENTORY_NEGATIVE:Y',
            'AD.APPROVED_DATE:S:APPROVED_DATE:N',
            'AD.APPROVED_SEQ:NZ:APPROVED_SEQ:N',
            'AD.PRICING_AMT:NZ:PRICING_AMT:N',
            'AD.CASH_ACTUAL_RECEIPT_AMT:NZ:CASH_ACTUAL_RECEIPT_AMT:N',
            'AD.CASH_RECEIPT_AMT:NZ:CASH_RECEIPT_AMT:N',
            'AD.PRIMARY_REVENUE_EXPENSE_AMT:NZ:PRIMARY_REVENUE_EXPENSE_AMT:N',
            'AD.PRIMARY_ITEM_DISCOUNT_AMT:NZ:PRIMARY_ITEM_DISCOUNT_AMT:N',
            'AD.PRIMARY_FINAL_DISCOUNT_AVG_AMT:NZ:PRIMARY_FINAL_DISCOUNT_AVG_AMT:N',
            'AD.RECEIPT_FLAG:S:RECEIPT_FLAG:Y',
            'AD.REF_DOCUMENT_NO:S:REF_DOCUMENT_NO:Y',
            'AD.ENTITY_ADDRESS_ID:REFID:ENTITY_ADDRESS_ID:N',
            'AD.RECEIPT_PAID_AMT:NZ:RECEIPT_PAID_AMT:N',
            'AD.RECEIPT_DEBT_AMT:NZ:RECEIPT_DEBT_AMT:N',
            'AD.ARAP_REMAIN_AMT:NZ:ARAP_REMAIN_AMT:N',
            'AD.ARAP_PAID_AMT:NZ:ARAP_PAID_AMT:N',
            'AD.ARAP_PAID_OFF_FLAG:S:ARAP_PAID_OFF_FLAG:Y',
            'AD.RECEIPT_ID:REFID:RECEIPT_ID:Y',
            'AD.IS_PROMOTION_MODE:S:IS_PROMOTION_MODE:Y',
            'AD.INDEX_DOC_INCLUDE:S:INDEX_DOC_INCLUDE:Y',
            'AD.CHANGE_TYPE:NZ:CHANGE_TYPE:Y',
            'AD.BY_VOID_FLAG:S:BY_VOID_FLAG:Y',
            'AD.WH_DEFINITION:S:WH_DEFINITION:N',
            'AD.PROJECT_ID:REFID:PROJECT_ID:Y',
            'AD.ACTUAL_TX_DATE:S:ACTUAL_TX_DATE:N',
            'AD.CASH_RECEIVE_AMT:NZ:CASH_RECEIVE_AMT:N',
            'AD.CASH_CHANGE_AMT:NZ:CASH_CHANGE_AMT:N',
            'AD.REF_WH_DOC_NO:S:REF_WH_DOC_NO:N',
            'AD.REF_PO_NO:S:REF_PO_NO:Y',
            'AD.REF_RECEIPT_NO:S:REF_RECEIPT_NO:N',
            'AD.CHEQUE_ID:REFID:CHEQUE_ID:Y',
            'AD.INVOICE_AVAILABLE_FLAG:S:INVOICE_AVAILABLE_FLAG:Y',
            'AD.WH_PAY_TYPE:NZ:WH_PAY_TYPE:N',
            'AD.REF_DOCUMENT_DATE:S:REF_DOCUMENT_DATE:Y',
            'AD.REF_QUOTATION_NO:S:REF_QUOTATION_NO:Y',
            'AD.VAT_MONTH_YEAR:S:VAT_MONTH_YEAR:N',
            'AD.WH_MONTH_YEAR:S:WH_MONTH_YEAR:Y',
            'AD.INTERNAL_DRCR_FLAG:S:INTERNAL_DRCR_FLAG:Y',
            'AD.REF_QUOTATION_ID:REFID:REF_QUOTATION_ID:Y',
            'AD.REF_SALE_ORDER_ID:REFID:REF_SALE_ORDER_ID:Y',
            'AD.REF_SALE_ORDER_NO:S:REF_SALE_ORDER_NO:Y', 
            'AD.SO_IN_USED_BY_INVOICE:S:SO_IN_USED_BY_INVOICE:Y',
            'AD.INDEX_PAYMENT:S:INDEX_PAYMENT:N',
            'AD.IS_APPROVED_DOC_NO:S:IS_APPROVED_DOC_NO:N',
            'AD.BILL_SUMMARY_ID:REFID:BILL_SUMMARY_ID:N',
            'AD.INDEX_PROJECT:S:INDEX_PROJECT:N',
            'AD.NOTE:S:NOTE:Y',
            'AD.DOCUMENT_YYYYMM:S:DOCUMENT_YYYYMM:N',
            'AD.DOCUMENT_YYYY:S:DOCUMENT_YYYY:N',
            'AD.VAT_CLAIMABLE:S:VAT_CLAIMABLE:Y',
            'AD.DRCR_FOR_EXPENSE_REVENUE:S:DRCR_FOR_EXPENSE_REVENUE:Y',
            'AD.REDEEM_DOCUMENT_ID:REFID:REDEEM_DOCUMENT_ID:N',

            'MR.DESCRIPTION:S:BRANCH_NAME:N',
            'MR.DESCRIPTION_ENG:S:BRANCH_NAME_ENG:N',
            'EN.ENTITY_CODE:S:ENTITY_CODE:Y',
            'EN.ENTITY_NAME:S:ENTITY_NAME:Y',
            'EN.CREDIT_TERM:NZ:CREDIT_TERM:Y',
            'EN.ENTITY_TYPE:REFID:ENTITY_TYPE:Y',
            'EN.ENTITY_GROUP:REFID:ENTITY_GROUP:Y',
            'EN.PHONE:S:ENTITY_PHONE:Y',
            'EN.FAX:S:ENTITY_FAX:Y',
            'EN.ID_NUMBER:S:ID_NUMBER:Y',
            'EN.RV_TAX_TYPE:N:RV_TAX_TYPE:N',

            'LC.LOCATION_CODE:S:LOCATION_CODE:N',
            'LC.DESCRIPTION:S:LOCATION_DESCRIPTION:N',
            'ID.DOCUMENT_NO:S:INVENTORY_DOC_NO:N',
            'CD.DOCUMENT_NO:S:CASH_DOC_NO:N',
            'CA.ACCOUNT_NO:S:ACCOUNT_NO:N',
            'CA.ACCOUNT_NNAME:S:ACCOUNT_NAME:N',
            'CQ.CHEQUE_NO:S:CHEQUE_NO:Y',
            'AD.FINAL_DISCOUNT:S:FINAL_DISCOUNT:N',
            'AD.EMPLOYEE_ID:N:EMPLOYEE_ID:Y',
            'EM.EMPLOYEE_CODE:S:EMPLOYEE_CODE:N',
            'EM.EMPLOYEE_NAME:S:EMPLOYEE_NAME:N',
            "CONCAT(EM.EMPLOYEE_NAME, ' ', EM.EMPLOYEE_LASTNAME):S:EMPLOYEE_NAME_LASTNAME:N:Y",
            'EA.ENTITY_ADDRESS:S:ENTITY_ADDRESS:N',
            'NP.DESCRIPTION:S:NAME_PREFIX_DESC:N',

            'PJ.PROJECT_CODE:S:PROJECT_CODE:Y',
            'PJ.PROJECT_NAME:S:PROJECT_NAME:Y',
            'PJ.PROJECT_DESC:S:PROJECT_DESC:Y',
            'PG.DESCRIPTION:S:PROJECT_GROUP_NAME:N',

            'BS.DOCUMENT_NO:S:BILL_SUMMARY_NO:N',
            
            # Always put these at the end
            'AD.DOCUMENT_DATE:FD:FROM_DOCUMENT_DATE:Y',
            'AD.DOCUMENT_DATE:TD:TO_DOCUMENT_DATE:Y',
            'AD.DUE_DATE:FD:FROM_DUE_DATE:Y',
            'AD.DUE_DATE:TD:TO_DUE_DATE:Y',    
            'AD.VAT_MONTH_YEAR:FD:FROM_MONTH_YEAR:Y',
            'AD.VAT_MONTH_YEAR:TD:TO_MONTH_YEAR:Y',                
            'AD.DOCUMENT_TYPE:INC_SET:DOCUMENT_TYPE_SET:Y',
            'AD.DOCUMENT_STATUS:INC_SET:DOCUMENT_STATUS_SET:Y',
            'AD.ACCOUNT_DOC_ID:EXC_SET:EXCLUDE_DOC_ID_SET:Y',
            'AD.RECEIPT_ID:IS_NULL:RECEIPT_ABLE_FLAG:Y',
            'AD.BILL_SUMMARY_ID:IS_NULL:BILLSUM_ABLE_FLAG:Y',
        ],

        [ # 2 For sum group by employee
            'EM.EMPLOYEE_ID:N:EMPLOYEE_ID:Y',
            'EM.EMPLOYEE_CODE:S:EMPLOYEE_CODE:Y',
            'EM.EMPLOYEE_NAME:S:EMPLOYEE_NAME:Y',
            'COUNT(AD.ACCOUNT_DOC_ID):NZ:TOTAL_BILL_COUNT:N',
            'SUM(AD.REVENUE_EXPENSE_AMT):NZ:TOTAL_BILL_AMT:N',

            # Always put these at the end
            'AD.DOCUMENT_TYPE:INC_SET:DOCUMENT_TYPE_SET:Y',
            'AD.DOCUMENT_DATE:FD:FROM_DOCUMENT_DATE:Y',
            'AD.DOCUMENT_DATE:TD:TO_DOCUMENT_DATE:Y',
            'AD.DUE_DATE:FD:FROM_DUE_DATE:Y',
            'AD.DUE_DATE:TD:TO_DUE_DATE:Y',
            'CM.COMMISSION_AMT:IS_NULL:IS_NULL_COMMISSION:Y',
        ],

        [ # 3 For update document type and status
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'DOCUMENT_STATUS:NZ:DOCUMENT_STATUS:N',
            'DOCUMENT_TYPE:NZ:DOCUMENT_TYPE:N',            
        ],        

        [ # 4 For updating paid off flag
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'ARAP_PAID_OFF_FLAG:S:ARAP_PAID_OFF_FLAG:N',        
        ],

        [ # 5 For updating receipt id
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'RECEIPT_ID:REFID:RECEIPT_ID:N',        
        ],
        
        [ # 6 For adjust document (post update)
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'DOCUMENT_DATE:S:DOCUMENT_DATE:N',
            'DOCUMENT_YYYY:S:DOCUMENT_YYYY:N',
            'DOCUMENT_YYYYMM:S:DOCUMENT_YYYYMM:N',
            'DUE_DATE:S:DUE_DATE:N',
            'DOCUMENT_DESC:S:DOCUMENT_DESC:N',
            'BRANCH_ID:REFID:BRANCH_ID:Y',
            'EMPLOYEE_ID:REFID:EMPLOYEE_ID:Y',
            'REF_DOCUMENT_NO:S:REF_DOCUMENT_NO:Y',
            'ENTITY_ADDRESS_ID:REFID:ENTITY_ADDRESS_ID:N',            
            'PROJECT_ID:REFID:PROJECT_ID:Y',
            'REF_WH_DOC_NO:S:REF_WH_DOC_NO:N',
            'REF_PO_NO:S:REF_PO_NO:Y',
            'REF_RECEIPT_NO:S:REF_RECEIPT_NO:N',
            'INVOICE_AVAILABLE_FLAG:S:INVOICE_AVAILABLE_FLAG:Y',
            'ACTUAL_TX_DATE:S:ACTUAL_TX_DATE:N',
            'WH_PAY_TYPE:NZ:WH_PAY_TYPE:N',
            'REF_DOCUMENT_DATE:S:REF_DOCUMENT_DATE:Y',
            'VAT_MONTH_YEAR:S:VAT_MONTH_YEAR:Y',
            'WH_MONTH_YEAR:S:WH_MONTH_YEAR:Y',
            'INDEX_PROJECT:S:INDEX_PROJECT:N',
            'VAT_CLAIMABLE:S:VAT_CLAIMABLE:N',
            'DRCR_FOR_EXPENSE_REVENUE:S:DRCR_FOR_EXPENSE_REVENUE:Y',

            'CREATE_DATE:CD:CREATE_DATE:N',
            'MODIFY_DATE:MD:MODIFY_DATE:N',
        ],
        
        [ # 7 For updating SO inused flag
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'SO_IN_USED_BY_INVOICE:S:SO_IN_USED_BY_INVOICE:N',        
        ],  
        
        [ # 8 Invoice Verification
            'AD.ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'AD.DOCUMENT_DATE:S:DOCUMENT_DATE:N',
            'AD.DUE_DATE:S:DUE_DATE:N',
            'AD.DOCUMENT_NO:S:DOCUMENT_NO:Y',
            'AD.DOCUMENT_DESC:S:DOCUMENT_DESC:Y',
            'AD.ENTITY_ID:REFID:ENTITY_ID:Y',
            'AD.LOCATION_ID:REFID:LOCATION_ID:Y',
            'AD.BRANCH_ID:REFID:BRANCH_ID:Y',
            'AD.ACCOUNT_SIDE:NZ:ACCOUNT_SIDE:Y',
            'AD.DOCUMENT_TYPE:NZ:DOCUMENT_TYPE:Y',
            'AD.DOCUMENT_STATUS:NZ:DOCUMENT_STATUS:Y',
            'AD.FINAL_DISCOUNT_AMT:NZ:FINAL_DISCOUNT_AMT:N',
            'AD.ITEM_DISCOUNT_AMT:NZ:ITEM_DISCOUNT_AMT:N',
            'AD.VAT_PCT:NZ:VAT_PCT:N',
            'AD.VAT_AMT:NZ:VAT_AMT:N',
            'AD.WH_TAX_AMT:NZ:WH_TAX_AMT:N',
            'AD.WH_TAX_PCT:NZ:WH_TAX_PCT:N',
            'AD.PAYMENT_TYPE:NZ:PAYMENT_TYPE:Y',
            'AD.INVENTORY_DOC_ID:REFID:INVENTORY_DOC_ID:Y',
            'AD.CASH_DOC_ID:REFID:CASH_DOC_ID:Y',
            'AD.AR_TX_TYPE:S:AR_TX_TYPE:Y',
            'AD.AR_TX_AMOUNT:NZ:AR_TX_AMOUNT:N',
            'AD.AR_BEGIN_AMOUNT:NZ:AR_BEGIN_AMOUNT:N',
            'AD.AR_END_AMOUNT:NZ:AR_END_AMOUNT:N',
            'AD.CASH_ACCOUNT_ID:REFID:CASH_ACCOUNT_ID:Y',
            'AD.BILL_SIMULATE_ID:REFID:BILL_SIMULATE_ID:N',
            'AD.PROMOTION_TOTAL_AMOUNT:NZ:PROMOTION_TOTAL_AMOUNT:N',
            'AD.PROMOTION_AMOUNT:NZ:PROMOTION_AMOUNT:N',
            'AD.PROMOTION_FINAL_DISCOUNT_AMOUNT:NZ:PROMOTION_FINAL_DISCOUNT_AMOUNT:N',
            'AD.PROMO_FREE_COUNT:NZ:PROMO_FREE_COUNT:N',
            'AD.PROMO_VOUCHER_COUNT:NZ:PROMO_VOUCHER_COUNT:N',
            'AD.PROMO_POSTFREE_COUNT:NZ:PROMO_POSTFREE_COUNT:N',
            'AD.REVENUE_EXPENSE_AMT:NZ:REVENUE_EXPENSE_AMT:N',
            'AD.REVENUE_EXPENSE_FOR_WH_AMT:NZ:REVENUE_EXPENSE_FOR_WH_AMT:N',
            'AD.REVENUE_EXPENSE_FOR_VAT_AMT:NZ:REVENUE_EXPENSE_FOR_VAT_AMT:N',
            'AD.AR_AP_AMT:NZ:AR_AP_AMT:N',
            'AD.VAT_TYPE:NZ:VAT_TYPE:N',
            'AD.ALLOW_AR_AP_NEGATIVE:S:ALLOW_AR_AP_NEGATIVE:Y',
            'AD.ALLOW_CASH_NEGATIVE:S:ALLOW_CASH_NEGATIVE:Y',
            'AD.ALLOW_INVENTORY_NEGATIVE:S:ALLOW_INVENTORY_NEGATIVE:Y',
            'AD.APPROVED_DATE:S:APPROVED_DATE:N',
            'AD.APPROVED_SEQ:NZ:APPROVED_SEQ:N',
            'AD.PRICING_AMT:NZ:PRICING_AMT:N',
            'AD.CASH_ACTUAL_RECEIPT_AMT:NZ:CASH_ACTUAL_RECEIPT_AMT:N',
            'AD.CASH_RECEIPT_AMT:NZ:CASH_RECEIPT_AMT:N',
            'AD.PRIMARY_REVENUE_EXPENSE_AMT:NZ:PRIMARY_REVENUE_EXPENSE_AMT:N',
            'AD.PRIMARY_ITEM_DISCOUNT_AMT:NZ:PRIMARY_ITEM_DISCOUNT_AMT:N',
            'AD.PRIMARY_FINAL_DISCOUNT_AVG_AMT:NZ:PRIMARY_FINAL_DISCOUNT_AVG_AMT:N',
            'AD.RECEIPT_FLAG:S:RECEIPT_FLAG:Y',
            'AD.REF_DOCUMENT_NO:S:REF_DOCUMENT_NO:Y',
            'AD.ENTITY_ADDRESS_ID:REFID:ENTITY_ADDRESS_ID:N',
            'AD.RECEIPT_PAID_AMT:NZ:RECEIPT_PAID_AMT:N',
            'AD.RECEIPT_DEBT_AMT:NZ:RECEIPT_DEBT_AMT:N',
            'AD.ARAP_REMAIN_AMT:NZ:ARAP_REMAIN_AMT:N',
            'AD.ARAP_PAID_AMT:NZ:ARAP_PAID_AMT:N',
            'AD.ARAP_PAID_OFF_FLAG:S:ARAP_PAID_OFF_FLAG:Y',
            'AD.RECEIPT_ID:REFID:RECEIPT_ID:Y',
            'AD.IS_PROMOTION_MODE:S:IS_PROMOTION_MODE:Y',
            'AD.INDEX_DOC_INCLUDE:S:INDEX_DOC_INCLUDE:Y',
            'AD.CHANGE_TYPE:NZ:CHANGE_TYPE:Y',
            'AD.BY_VOID_FLAG:S:BY_VOID_FLAG:Y',
            'AD.WH_DEFINITION:S:WH_DEFINITION:N',
            'AD.PROJECT_ID:REFID:PROJECT_ID:Y',
            'AD.ACTUAL_TX_DATE:S:ACTUAL_TX_DATE:N',
            'AD.CASH_RECEIVE_AMT:NZ:CASH_RECEIVE_AMT:N',
            'AD.CASH_CHANGE_AMT:NZ:CASH_CHANGE_AMT:N',
            'AD.REF_WH_DOC_NO:S:REF_WH_DOC_NO:N',
            'AD.REF_PO_NO:S:REF_PO_NO:Y',
            'AD.REF_RECEIPT_NO:S:REF_RECEIPT_NO:N',
            'AD.CHEQUE_ID:REFID:CHEQUE_ID:Y',
            'AD.INVOICE_AVAILABLE_FLAG:S:INVOICE_AVAILABLE_FLAG:Y',
            'AD.WH_PAY_TYPE:NZ:WH_PAY_TYPE:N',
            'AD.REF_DOCUMENT_DATE:S:REF_DOCUMENT_DATE:Y',
            'AD.REF_QUOTATION_NO:S:REF_QUOTATION_NO:Y',
            'AD.VAT_MONTH_YEAR:S:VAT_MONTH_YEAR:N',
            'AD.WH_MONTH_YEAR:S:WH_MONTH_YEAR:Y',
            'AD.INTERNAL_DRCR_FLAG:S:INTERNAL_DRCR_FLAG:Y',
            'AD.REF_QUOTATION_ID:REFID:REF_QUOTATION_ID:Y',
            'AD.REF_SALE_ORDER_ID:REFID:REF_SALE_ORDER_ID:Y',
            'AD.REF_SALE_ORDER_NO:S:REF_SALE_ORDER_NO:Y', 
            'AD.SO_IN_USED_BY_INVOICE:S:SO_IN_USED_BY_INVOICE:Y',
            'AD.INDEX_PAYMENT:S:INDEX_PAYMENT:N',
            'AD.IS_APPROVED_DOC_NO:S:IS_APPROVED_DOC_NO:N',
            'AD.BILL_SUMMARY_ID:REFID:BILL_SUMMARY_ID:N',
            'AD.INDEX_PROJECT:S:INDEX_PROJECT:N',
            'AD.NOTE:S:NOTE:Y',
            'AD.DOCUMENT_YYYYMM:S:DOCUMENT_YYYYMM:N',
            'AD.DOCUMENT_YYYY:S:DOCUMENT_YYYY:N',
            'AD.VAT_CLAIMABLE:S:VAT_CLAIMABLE:Y',
            'AD.DRCR_FOR_EXPENSE_REVENUE:S:DRCR_FOR_EXPENSE_REVENUE:Y',
            'AD.REDEEM_DOCUMENT_ID:REFID:REDEEM_DOCUMENT_ID:N',
                        
            'EN.ENTITY_CODE:S:ENTITY_CODE:Y',
            'EN.ENTITY_NAME:S:ENTITY_NAME:Y',
            'EN.CREDIT_TERM:NZ:CREDIT_TERM:Y',
            'EN.ENTITY_TYPE:REFID:ENTITY_TYPE:Y',
            'EN.ENTITY_GROUP:REFID:ENTITY_GROUP:Y',
            'EN.PHONE:S:ENTITY_PHONE:Y',
            'EN.FAX:S:ENTITY_FAX:Y',
            'EN.ID_NUMBER:S:ID_NUMBER:Y',
            'EN.RV_TAX_TYPE:N:RV_TAX_TYPE:N',

            'PJ.PROJECT_CODE:S:PROJECT_CODE:Y',
            'PJ.PROJECT_NAME:S:PROJECT_NAME:Y',
            'PJ.PROJECT_DESC:S:PROJECT_DESC:Y',

            'PG.CODE:S:PROJECT_GROUP_CODE:Y',
            'PG.DESCRIPTION:S:PROJECT_GROUP_NAME:Y',
                        
            'RC.DOCUMENT_NO:S:RECEIPT_NO:Y',
            'RC.DOCUMENT_DATE:S:RECEIPT_DATE:Y',
            'RC.INDEX_PAYMENT:S:RECEIPT_INDEX_PAYMENT:Y',

            # Always put these at the end
            'AD.DOCUMENT_DATE:FD:FROM_DOCUMENT_DATE:Y',
            'AD.DOCUMENT_DATE:TD:TO_DOCUMENT_DATE:Y',
            'AD.DUE_DATE:FD:FROM_DUE_DATE:Y',
            'AD.DUE_DATE:TD:TO_DUE_DATE:Y',    
            'AD.VAT_MONTH_YEAR:FD:FROM_MONTH_YEAR:Y',
            'AD.VAT_MONTH_YEAR:TD:TO_MONTH_YEAR:Y',                
            'AD.DOCUMENT_TYPE:INC_SET:DOCUMENT_TYPE_SET:Y',
            'AD.DOCUMENT_STATUS:INC_SET:DOCUMENT_STATUS_SET:Y',
            'AD.ACCOUNT_DOC_ID:EXC_SET:EXCLUDE_DOC_ID_SET:Y',
            'AD.RECEIPT_ID:IS_NULL:RECEIPT_ABLE_FLAG:Y',
        ],  
        
        [ # 9 Update payment index
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'INDEX_PAYMENT:S:INDEX_PAYMENT:N',
            'INDEX_PROJECT:S:INDEX_PROJECT:N',
        ],

        [ # 10 For updating bill summary id
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'BILL_SUMMARY_ID:REFID:BILL_SUMMARY_ID:N',        
        ],  
        
        [ # 11 Profit By Month Report
            'AD.DOCUMENT_TYPE:N:DOCUMENT_TYPE:N',
            'AD.DOCUMENT_YYYYMM:S:DOCUMENT_YYYYMM:Y',
            'AD.DOCUMENT_YYYY:S:DOCUMENT_YYYY:Y',
            'AD.DOCUMENT_STATUS:NZ:DOCUMENT_STATUS:Y:N',
            'AD.BY_VOID_FLAG:S:BY_VOID_FLAG:Y:N',
            'AD.INTERNAL_DRCR_FLAG:S:INTERNAL_DRCR_FLAG:Y:N',

            'SUM(ROUND(AD.REVENUE_EXPENSE_AMT, 2)):NZ:REVENUE_EXPENSE_AMT:N',
            'SUM(ROUND(AD.REVENUE_EXPENSE_FOR_WH_AMT, 2)):NZ:REVENUE_EXPENSE_FOR_WH_AMT:N',
            'SUM(ROUND(AD.REVENUE_EXPENSE_FOR_VAT_AMT, 2)):NZ:REVENUE_EXPENSE_FOR_VAT_AMT:N',
            'SUM(ROUND(AD.VAT_AMT, 2)):NZ:VAT_AMT:N',
            'SUM(ROUND(AD.WH_TAX_AMT, 2)):NZ:WH_TAX_AMT:N',
 
            # Always put these at the end
            'AD.DOCUMENT_DATE:FD:FROM_DOCUMENT_DATE:Y',
            'AD.DOCUMENT_DATE:TD:TO_DOCUMENT_DATE:Y',
            'AD.DOCUMENT_TYPE:INC_SET:DOCUMENT_TYPE_SET:Y',
            'AD.DOCUMENT_STATUS:INC_SET:DOCUMENT_STATUS_SET:Y',                      
        ],   
        
        [ # 12 For unlink sale order
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'SO_IN_USED_BY_INVOICE:S:SO_IN_USED_BY_INVOICE:N',        
        ],

        [ # 13 For unlink sale order
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'REF_SALE_ORDER_ID:REFID:REF_SALE_ORDER_ID:N',        
        ], 

        [ # 14 For update redeem document
            'ACCOUNT_DOC_ID:SPK:ACCOUNT_DOC_ID:Y',
            'REDEEM_DOCUMENT_ID:REFID:REDEEM_DOCUMENT_ID:N',        
        ],        
                 
    );

    private $froms = array(

        'FROM ACCOUNT_DOC ',

        'FROM ACCOUNT_DOC AD '.
            'LEFT OUTER JOIN PROJECT PJ ON (AD.PROJECT_ID = PJ.PROJECT_ID) '.      
            'LEFT OUTER JOIN MASTER_REF PG ON (PG.MASTER_ID = PJ.PROJECT_GROUP) '.  
            'LEFT OUTER JOIN ENTITY EN ON (EN.ENTITY_ID = AD.ENTITY_ID) '.
            'LEFT OUTER JOIN LOCATION LC ON (LC.LOCATION_ID = AD.LOCATION_ID) '.
            'LEFT OUTER JOIN MASTER_REF MR ON (MR.MASTER_ID = AD.BRANCH_ID) '.
            'LEFT OUTER JOIN INVENTORY_DOC ID ON (ID.DOC_ID = AD.INVENTORY_DOC_ID) '.
            'LEFT OUTER JOIN CASH_DOC CD ON (CD.CASH_DOC_ID = AD.CASH_DOC_ID) '.
            'LEFT OUTER JOIN CHEQUE CQ ON (AD.CHEQUE_ID = CQ.CHEQUE_ID) '.
            'LEFT OUTER JOIN EMPLOYEE EM ON (EM.EMPLOYEE_ID = AD.EMPLOYEE_ID) '.
            'LEFT OUTER JOIN CASH_ACCOUNT CA ON (CA.CASH_ACCOUNT_ID = AD.CASH_ACCOUNT_ID) '.
            'LEFT OUTER JOIN MASTER_REF NP ON (NP.MASTER_ID = EN.NAME_PREFIX) '.
            'LEFT OUTER JOIN ACCOUNT_DOC BS ON (AD.BILL_SUMMARY_ID = BS.ACCOUNT_DOC_ID) '.
            'LEFT OUTER JOIN ENTITY_ADDRESS EA ON (AD.ENTITY_ADDRESS_ID = EA.ENTITY_ADDRESS_ID) ',

        'FROM ACCOUNT_DOC AD '.
            'LEFT OUTER JOIN EMPLOYEE EM ON (EM.EMPLOYEE_ID = AD.EMPLOYEE_ID) '.
            'LEFT OUTER JOIN COMMISSION CM ON (CM.ACCOUNT_DOC_ID = AD.ACCOUNT_DOC_ID) ',

        'FROM ACCOUNT_DOC ',

        'FROM ACCOUNT_DOC ',
        
        'FROM ACCOUNT_DOC ',
        
        'FROM ACCOUNT_DOC ',

        'FROM ACCOUNT_DOC ',

        'FROM ACCOUNT_DOC AD '.
            'LEFT OUTER JOIN ACCOUNT_DOC RC ON (RC.ACCOUNT_DOC_ID = AD.RECEIPT_ID) '. 
            'LEFT OUTER JOIN PROJECT PJ ON (AD.PROJECT_ID = PJ.PROJECT_ID) '.     
            'LEFT OUTER JOIN MASTER_REF PG ON (PJ.PROJECT_GROUP = PG.MASTER_ID) '.             
            'LEFT OUTER JOIN ENTITY EN ON (EN.ENTITY_ID = AD.ENTITY_ID) ',

        'FROM ACCOUNT_DOC ',    
        
        'FROM ACCOUNT_DOC ',

        'FROM ACCOUNT_DOC AD ',

        'FROM ACCOUNT_DOC AD ',

        'FROM ACCOUNT_DOC AD ',

        'FROM ACCOUNT_DOC AD ',
    );

    private $orderby = array(

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY AD.ACCOUNT_DOC_ID DESC ',

                'GROUP BY EM.EMPLOYEE_ID ORDER BY EM.EMPLOYEE_ID DESC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'GROUP BY AD.DOCUMENT_TYPE, AD.DOCUMENT_YYYYMM, AD.DOCUMENT_YYYY ' . 
                    'ORDER BY AD.DOCUMENT_TYPE ASC, AD.DOCUMENT_YYYYMM ',       
                    
                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',

                'ORDER BY ACCOUNT_DOC_ID ASC ',
    );

    function __construct($db)
    {
        parent::__construct($db, 'ACCOUNT_DOC', 'ACCOUNT_DOC_ID', $this->cols, $this->froms, $this->orderby);
    }
}
?>