<?php
/*
Purpose : Model for AUXILARY_DOC
Created By : Seubpong Monsar
Created Date : 01/11/2018 (MM/DD/YYYY)
IBSVer : 1.0
*/

declare(strict_types=1);

require_once "phar://onix_erp_framework.phar/onix_erp_include.php";

class MAuxilaryDoc extends MBaseModel
{
    private $cols = array(

        [ # 0 For insert, update, delete
            'AUXILARY_DOC_ID:SPK:AUXILARY_DOC_ID:Y',
            'DOCUMENT_DATE:S:DOCUMENT_DATE:N',
            'DELIVERY_DATE:S:DELIVERY_DATE:N',
            'DOCUMENT_NO:S:DOCUMENT_NO:Y',
            'DOCUMENT_STATUS:N:DOCUMENT_STATUS:Y',
            'DOCUMENT_TYPE:N:DOCUMENT_TYPE:Y',
            'NOTE:S:NOTE:N',
            'REF_DOC_NO:S:REF_DOC_NO:N',
            'SHIFT_TO:S:SHIFT_TO:N',
            'PROJECT_ID:REFID:PROJECT_ID:N',
            'ENTITY_ID:REFID:ENTITY_ID:N',
            'ENTITY_ADDRESS_ID:REFID:ENTITY_ADDRESS_ID:N',
            'BRANCH_ID:REFID:BRANCH_ID:N',
            'PAYMENT_TYPE:REFID:PAYMENT_TYPE:N',
            'VAT_PERCENTAGE:NZ:VAT_PERCENTAGE:N',
            'VAT_TYPE:NZ:VAT_TYPE:N',
            'VAT_AMT:NZ:VAT_AMT:N',
            'WH_TAX_AMT:NZ:WH_TAX_AMT:N',
            'ITEM_DISCOUNT_AMT:NZ:ITEM_DISCOUNT_AMT:N',
            'QUANTITY:NZ:QUANTITY:N',
            'PRIMARY_REVENUE_EXPENSE_AMT:NZ:PRIMARY_REVENUE_EXPENSE_AMT:N',
            'PRIMARY_ITEM_DISCOUNT_AMT:NZ:PRIMARY_ITEM_DISCOUNT_AMT:N',
            'PRIMARY_FINAL_DISCOUNT_AVG_AMT:NZ:PRIMARY_FINAL_DISCOUNT_AVG_AMT:N',
            'AR_AP_AMT:NZ:AR_AP_AMT:N',
            'CASH_RECEIPT_AMT:NZ:CASH_RECEIPT_AMT:N',
            'CASH_ACTUAL_RECEIPT_AMT:NZ:CASH_ACTUAL_RECEIPT_AMT:N',
            'REVENUE_EXPENSE_AMT:NZ:REVENUE_EXPENSE_AMT:N',
            'PRICING_AMT:NZ:PRICING_AMT:N',
            'FINAL_DISCOUNT:NZ:FINAL_DISCOUNT:N',                  
            'BANK_ACCOUNT_ID:REFID:BANK_ACCOUNT_ID:N',
            'EMPLOYEE_ID:REFID:EMPLOYEE_ID:N',
            'CURRENCY_ID:REFID:CURRENCY_ID:N',
            'PAYMENT_TERM:REFID:PAYMENT_TERM:N',
            'DAY_VALIDITY:NZ:DAY_VALIDITY:N',
            'PMT_VAT_AMT:NZ:PMT_VAT_AMT:N',
            'PMT_VAT_INCLUDE_AMT:NZ:PMT_VAT_INCLUDE_AMT:N',
            'PMT_REVENUE_EXPENSE:NZ:PMT_REVENUE_EXPENSE:N',
            'PMT_REMAIN_AMT:NZ:PMT_REMAIN_AMT:N',
            'PMT_WH_TAX_AMT:NZ:PMT_WH_TAX_AMT:N',
            'PO_INVOICE_REF_TYPE:REFID:PO_INVOICE_REF_TYPE:Y',
            'IN_USED_BY_SO:S:IN_USED_BY_SO:Y',
            'QUOTATION_TYPE:NZ:QUOTATION_TYPE:Y',                  
            'CONTACT_PERSON:S:CONTACT_PERSON:N',
            'REVISE_NO:S:REVISE_NO:N',
            'NOTE_WIDTH:NZ:NOTE_WIDTH:N',
            'NOTE_HEIGHT:NZ:NOTE_HEIGHT:N',
            'NOTE_TOP:NZ:NOTE_TOP:N',
            'NOTE_LEFT:NZ:NOTE_LEFT:N',            
            'NOTE_TEXT:S:NOTE_TEXT:N',
            'NOTE_STICK_FLAG:S:NOTE_STICK_FLAG:N',
            'CREDIT_TERM:NZ:CREDIT_TERM:N',
            'INDEX_ITEMS:S:INDEX_ITEMS:Y:N',
            'CREDIT_TERM_ID:REFID:CREDIT_TERM_ID:N',

            'CREATE_DATE:CD:CREATE_DATE:N',
            'MODIFY_DATE:MD:MODIFY_DATE:N',
        ],

        [ # For Get auxiliary doc List
            'AD.AUXILARY_DOC_ID:SPK:AUXILARY_DOC_ID:Y',
            'AD.DOCUMENT_DATE:S:DOCUMENT_DATE:N',
            'AD.DELIVERY_DATE:S:DELIVERY_DATE:N',
            'AD.DOCUMENT_NO:S:DOCUMENT_NO:Y',
            'AD.DOCUMENT_STATUS:N:DOCUMENT_STATUS:Y',
            'AD.DOCUMENT_TYPE:N:DOCUMENT_TYPE:Y',
            'AD.NOTE:S:NOTE:Y',
            'AD.REF_DOC_NO:S:REF_DOC_NO:N',
            'AD.SHIFT_TO:S:SHIFT_TO:N',
            'AD.PROJECT_ID:REFID:PROJECT_ID:N',
            'AD.ENTITY_ID:REFID:ENTITY_ID:N',
            'AD.ENTITY_ADDRESS_ID:REFID:ENTITY_ADDRESS_ID:N',
            'AD.BRANCH_ID:REFID:BRANCH_ID:N',
            'AD.PAYMENT_TYPE:REFID:PAYMENT_TYPE:N',
            'AD.VAT_PERCENTAGE:NZ:VAT_PERCENTAGE:N',
            'AD.VAT_TYPE:NZ:VAT_TYPE:N',
            'AD.VAT_AMT:NZ:VAT_AMT:N',
            'AD.WH_TAX_AMT:NZ:WH_TAX_AMT:N',
            'AD.ITEM_DISCOUNT_AMT:NZ:ITEM_DISCOUNT_AMT:N',
            'AD.QUANTITY:NZ:QUANTITY:N',
            'AD.PRIMARY_REVENUE_EXPENSE_AMT:NZ:PRIMARY_REVENUE_EXPENSE_AMT:N',
            'AD.PRIMARY_ITEM_DISCOUNT_AMT:NZ:PRIMARY_ITEM_DISCOUNT_AMT:N',
            'AD.PRIMARY_FINAL_DISCOUNT_AVG_AMT:NZ:PRIMARY_FINAL_DISCOUNT_AVG_AMT:N',
            'AD.AR_AP_AMT:NZ:AR_AP_AMT:N',
            'AD.CASH_RECEIPT_AMT:NZ:CASH_RECEIPT_AMT:N',
            'AD.CASH_ACTUAL_RECEIPT_AMT:NZ:CASH_ACTUAL_RECEIPT_AMT:N',
            'AD.REVENUE_EXPENSE_AMT:NZ:REVENUE_EXPENSE_AMT:N',
            'AD.PRICING_AMT:NZ:PRICING_AMT:N',
            'AD.FINAL_DISCOUNT:NZ:FINAL_DISCOUNT:N', 
            'AD.BANK_ACCOUNT_ID:REFID:BANK_ACCOUNT_ID:N',
            'AD.EMPLOYEE_ID:REFID:EMPLOYEE_ID:N',
            'AD.CURRENCY_ID:REFID:CURRENCY_ID:N',
            'AD.PAYMENT_TERM:REFID:PAYMENT_TERM:N',
            'AD.DAY_VALIDITY:NZ:DAY_VALIDITY:N',
            'AD.PMT_VAT_AMT:NZ:PMT_VAT_AMT:N',
            'AD.PMT_VAT_INCLUDE_AMT:NZ:PMT_VAT_INCLUDE_AMT:N',
            'AD.PMT_REVENUE_EXPENSE:NZ:PMT_REVENUE_EXPENSE:N',
            'AD.PMT_REMAIN_AMT:NZ:PMT_REMAIN_AMT:N',
            'AD.PMT_WH_TAX_AMT:NZ:PMT_WH_TAX_AMT:N',
            'AD.PO_INVOICE_REF_TYPE:REFID:PO_INVOICE_REF_TYPE:Y',
            'AD.IN_USED_BY_SO:S:IN_USED_BY_SO:Y',
            'AD.QUOTATION_TYPE:NZ:QUOTATION_TYPE:Y',
            'AD.CONTACT_PERSON:S:CONTACT_PERSON:Y',
            'AD.REVISE_NO:S:REVISE_NO:N',
            'AD.NOTE_WIDTH:NZ:NOTE_WIDTH:N',
            'AD.NOTE_HEIGHT:NZ:NOTE_HEIGHT:N',
            'AD.NOTE_TOP:NZ:NOTE_TOP:N',
            'AD.NOTE_LEFT:NZ:NOTE_LEFT:N',                 
            'AD.NOTE_TEXT:S:NOTE_TEXT:N',
            'AD.NOTE_STICK_FLAG:S:NOTE_STICK_FLAG:N',
            'AD.CREDIT_TERM:NZ:CREDIT_TERM:N',
            'AD.INDEX_ITEMS:S:INDEX_ITEMS:Y:N',
            'AD.CREDIT_TERM_ID:REFID:CREDIT_TERM_ID:N',

            'EM.EMPLOYEE_CODE:S:EMPLOYEE_CODE:N',
            'EM.EMPLOYEE_NAME:S:EMPLOYEE_NAME:N',
            'EM.EMPLOYEE_NAME_ENG:S:EMPLOYEE_NAME_ENG:N',
            'PT.DESCRIPTION:S:PAYMENT_TERM_NAME:N',
            'PT.DESCRIPTION_ENG:S:PAYMENT_TERM_NAME_ENG:N',
            'PT.CODE:S:PAYMENT_TERM_ODE:N',
            'CC.DESCRIPTION:S:CURRENCY_NAME:N',
            'CC.DESCRIPTION_ENG:S:CURRENCY_NAME_ENG:N',
            'CC.OPTIONAL:S:CURRENCY_SUB_NAME:N',
            'CC.OPTIONAL_ENG:S:CURRENCY_SUB_NAME_ENG:N',
            'CC.CODE:S:CURRENCY_CODE:N',

            'BR.DESCRIPTION:S:BRANCH_NAME:N',
            'BR.DESCRIPTION_ENG:S:BRANCH_NAME_ENG:N',

            'CT.DESCRIPTION:S:CREDIT_TERM_NAME:N',

            'EN.ENTITY_CODE:S:ENTITY_CODE:Y',
            'EN.ENTITY_NAME:S:ENTITY_NAME:Y',
            'EN.ENTITY_TYPE:REFID:ENTITY_TYPE:Y',
            'EN.ENTITY_GROUP:REFID:ENTITY_GROUP:Y',
            'EN.PHONE:S:ENTITY_PHONE:Y',
            'EN.FAX:S:FAX:Y',
            'EN.ID_NUMBER:S:ID_NUMBER:Y',
            'EN.PROMPT_PAY_ID:S:PROMPT_PAY_ID:Y',

            'EBA.ACCOUNT_NO:S:ACCOUNT_NO:Y',
            'BN.DESCRIPTION:S:BANK_NAME:Y',

            'AD.FINAL_DISCOUNT:S:FINAL_DISCOUNT:N',
            'EA.ENTITY_ADDRESS:S:ENTITY_ADDRESS:N',
            'NP.DESCRIPTION:S:NAME_PREFIX_DESC:N',

            'PJ.PROJECT_CODE:S:PROJECT_CODE:Y',
            'PJ.PROJECT_NAME:S:PROJECT_NAME:Y',
            'PJ.PROJECT_DESC:S:PROJECT_DESC:Y',
            'PG.DESCRIPTION:S:PROJECT_GROUP_NAME:N',

            # Always put these at the end
            'AD.DOCUMENT_DATE:FD:FROM_DOCUMENT_DATE:Y',
            'AD.DOCUMENT_DATE:TD:TO_DOCUMENT_DATE:Y',
            'AD.DELIVERY_DATE:FD:FROM_DELIVERY_DATE:Y',
            'AD.DELIVERY_DATE:TD:TO_DELIVERY_DATE:Y',
        ],

        [ # 2 For in_used_by_so flag
            'AUXILARY_DOC_ID:SPK:AUXILARY_DOC_ID:Y',
            'IN_USED_BY_SO:S:IN_USED_BY_SO:N',        
        ],
        
        [ # 3 Update items index
            'AUXILARY_DOC_ID:SPK:AUXILARY_DOC_ID:Y',
            'INDEX_ITEMS:S:INDEX_ITEMS:N',
        ],        
    );

    private $froms = array(
        
        'FROM AUXILARY_DOC ',

        'FROM AUXILARY_DOC AD '.
            'LEFT OUTER JOIN PROJECT PJ ON (AD.PROJECT_ID = PJ.PROJECT_ID) '.
            'LEFT OUTER JOIN ENTITY EN ON (EN.ENTITY_ID = AD.ENTITY_ID) '.
            'LEFT OUTER JOIN MASTER_REF BR ON (BR.MASTER_ID = AD.BRANCH_ID) '.
            'LEFT OUTER JOIN MASTER_REF NP ON (NP.MASTER_ID = EN.NAME_PREFIX) '.
            'LEFT OUTER JOIN MASTER_REF PG ON (PG.MASTER_ID = PJ.PROJECT_GROUP) '.
            'LEFT OUTER JOIN MASTER_REF PT ON (AD.PAYMENT_TERM = PT.MASTER_ID) '.
            'LEFT OUTER JOIN MASTER_REF CC ON (AD.CURRENCY_ID = CC.MASTER_ID) '.
            'LEFT OUTER JOIN EMPLOYEE EM ON (AD.EMPLOYEE_ID = EM.EMPLOYEE_ID) '.
            'LEFT OUTER JOIN ENTITY_BANK_ACCOUNT EBA ON (AD.BANK_ACCOUNT_ID = EBA.ENTITY_BACCT_ID) '.
            'LEFT OUTER JOIN MASTER_REF BN ON (BN.MASTER_ID = EBA.BANK_ID) '.
            'LEFT OUTER JOIN MASTER_REF CT ON (CT.MASTER_ID = AD.CREDIT_TERM_ID) '.
            'LEFT OUTER JOIN ENTITY_ADDRESS EA ON (AD.ENTITY_ADDRESS_ID = EA.ENTITY_ADDRESS_ID) ',

        'FROM AUXILARY_DOC ',       
        
        'FROM AUXILARY_DOC ',
    );

    private $orderby = array(

        'ORDER BY AUXILARY_DOC_ID ASC ',
        'ORDER BY AD.AUXILARY_DOC_ID DESC ',
        'ORDER BY AUXILARY_DOC_ID ASC ',
        'ORDER BY AUXILARY_DOC_ID ASC ',
    );

    function __construct($db)
    {
        parent::__construct($db, 'AUXILARY_DOC', 'AUXILARY_DOC_ID', $this->cols, $this->froms, $this->orderby);
    }
}

?>