
INSERT INTO USER_GROUP (GROUP_ID, GROUP_NAME, DESCRIPTION, CREATE_DATE, MODIFY_DATE) VALUES (99999, 'ADMIN', 'ADMIN', '2017/03/23 00:00:00', '2017/03/23 00:00:00');

INSERT INTO USERS 
(USER_ID, USER_NAME, DESCRIPTION, PASSWORD, IS_ENABLE, IS_ADMIN, GROUP_ID, CREATE_DATE, MODIFY_DATE) 
VALUES 
(99999, 'ADMIN', 'Admin - auto created', '1234', 'Y', 'Y', 99999, '2017/03/23 00:00:00', '2017/03/23 00:00:00');

ALTER TABLE ITEM ADD COLUMN NOTE TEXT;

ALTER TABLE ITEM ADD COLUMN SALE_UOM INTEGER;

ALTER TABLE ITEM ADD FOREIGN KEY(SALE_UOM) REFERENCES MASTER_REF(MASTER_ID);

ALTER TABLE ITEM ADD COLUMN MINIMUM_ALLOW NUMERIC(10,2);

CREATE TABLE LOGIN_SESSION
(
    LOGIN_ID             INTEGER NOT NULL,
    LOGIN_SESSION        TEXT,
    
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL    
);

CREATE TABLE ENTITY
(
    ENTITY_ID          INTEGER NOT NULL PRIMARY KEY,
    ENTITY_CODE        TEXT NOT NULL UNIQUE,
    ENTITY_NAME        TEXT NOT NULL,
    ADDRESS            TEXT NOT NULL,
    EMAIL              TEXT,
    WEBSITE            TEXT,
    PHONE              TEXT,
    FAX                TEXT,
    ENTITY_TYPE        INTEGER NOT NULL,
    ENTITY_GROUP       INTEGER NOT NULL,
    NOTE               TEXT,
    CREDIT_TERM        INTEGER NOT NULL,
    CREDIT_LIMIT       NUMERIC(10,2),
    CATEGORY           INTEGER NOT NULL,  /* 1=Customer, 2=Supplier */
    
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL,
    
    FOREIGN KEY(ENTITY_TYPE) REFERENCES MASTER_REF(MASTER_ID),   
    FOREIGN KEY(ENTITY_GROUP) REFERENCES MASTER_REF(MASTER_ID)
);

CREATE TABLE USER_VARIABLE
(
    VARIABLE_ID        INTEGER NOT NULL PRIMARY KEY,
    VARIABLE_NAME      TEXT NOT NULL UNIQUE,
    VARIABLE_VALUE     TEXT NOT NULL,
    USER_ID            INTEGER NOT NULL,
    
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL,
    
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE SERVICE
(
    SERVICE_ID           INTEGER NOT NULL PRIMARY KEY,
    SERVICE_CODE         TEXT NOT NULL UNIQUE,
    SERVICE_NAME         TEXT NOT NULL,
    SERVICE_TYPE         INTEGER NOT NULL,
    SERVICE_UOM          INTEGER NOT NULL,
    SERVICE_CATEGORY     INTEGER NOT NULL, /* 1 = sale, 2 = purchase, 3 = both */
            
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL,
    
    FOREIGN KEY(SERVICE_TYPE) REFERENCES MASTER_REF(MASTER_ID),   
    FOREIGN KEY(SERVICE_UOM) REFERENCES MASTER_REF(MASTER_ID)
);   

CREATE TABLE INVENTORY_LOT
(
    INV_LOT_ID           INTEGER NOT NULL PRIMARY KEY,
    LOT_DATE             CHAR(19) NOT NULL,
    LOT_NO               TEXT,
    LOT_DESC             TEXT,
    LOT_KEY              TEXT NOT NULL UNIQUE,
    LOT_LEVEL            INTEGER NOT NULL,
    LOCATION_ID          INTEGER NOT NULL,
    ITEM_ID              INTEGER NOT NULL,
    TRACKING_HISTORY     TEXT,
    QUANTITY             NUMERIC(10,2) NOT NULL,
    AMOUNT               NUMERIC(10,2) NOT NULL,

    AMOUNT_PER_UNIT      NUMERIC(10,2) NOT NULL,
    ANNONYMOUS_FLAG      TEXT NOT NULL,

            
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL,
    
    FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),   
    FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID)
);   