

CREATE TABLE DOCUMENT_NUMBER
(
    DOCUMENT_NUMBER_ID   INTEGER NOT NULL PRIMARY KEY,
    DOC_TYPE             TEXT NOT NULL UNIQUE,    
    LAST_RUN_YEAR        INTEGER, /* Century */
    LAST_RUN_MONTH       INTEGER, /* Century */    
    FORMULA              TEXT NOT NULL,
    RESET_CRITERIA       INTEGER NOT NULL, /* 1=Monthly, 2=Yearly */
    CURRENT_SEQ          INTEGER NOT NULL,
    START_SEQ            INTEGER NOT NULL,
    SEQ_LENGTH           INTEGER NOT NULL,    
    YEAR_OFFSET          INTEGER NOT NULL, /* 543 */
               
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL      
);

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(1, 'INVENTORY_DOC_IMPORT_TEMP', 2017, 5, 'IMP-TMP-${yyyy}-${seq}', 2, 0, 1, 4, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(2, 'INVENTORY_DOC_IMPORT_APPROVED', 2017, 5, 'IMP-APR-${yyyy}-${seq}', 2, 0, 1, 4, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(3, 'INVENTORY_DOC_EXPORT_TEMP', 2017, 5, 'EXP-TMP-${yyyy}-${seq}', 2, 0, 1, 5, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(4, 'INVENTORY_DOC_EXPORT_APPROVED', 2017, 5, 'EXP-APR-${yyyy}-${seq}', 2, 0, 1, 5, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(5, 'INVENTORY_DOC_EXFER_TEMP', 2017, 5, 'XFR-TMP-${yyyy}-${seq}', 2, 0, 1, 5, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(6, 'INVENTORY_DOC_EXFER_APPROVED', 2017, 5, 'XFR-APR-${yyyy}-${seq}', 2, 0, 1, 5, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(7, 'INVENTORY_DOC_ADJ_TEMP', 2017, 5, 'ADJ-TMP-${yyyy}-${seq}', 2, 0, 1, 5, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');

INSERT INTO DOCUMENT_NUMBER 
(DOCUMENT_NUMBER_ID, DOC_TYPE, LAST_RUN_YEAR, LAST_RUN_MONTH, FORMULA, RESET_CRITERIA, CURRENT_SEQ, START_SEQ, SEQ_LENGTH, YEAR_OFFSET, CREATE_DATE, MODIFY_DATE) 
VALUES 
(8, 'INVENTORY_DOC_ADJ_APPROVED', 2017, 5, 'ADJ-APR-${yyyy}-${seq}', 2, 0, 1, 5, 0, '2017/05/25 00:00:00', '2017/05/25 00:00:00');
