
ALTER TABLE INVENTORY_DOC ADD COLUMN FINAL_DISCOUNT NUMERIC(10,2);

ALTER TABLE INVENTORY_DOC ADD COLUMN VAT_PCT NUMERIC(10,2);

ALTER TABLE INVENTORY_DOC ADD COLUMN TOTAL_AMOUNT NUMERIC(10,2);


/* UI_TOTAL_AMOUNT = UI_ITEM_AMOUNT - UI_ITEM_DISCOUNT - UI_WEIGHT_DISCOUNT */
/* UI_ITEM_AMOUNT = UI_ITEM_UNIT_PRICE * ITEM_QUANTYT */

ALTER TABLE INVENTORY_TX ADD COLUMN UI_ITEM_UNIT_PRICE NUMERIC(10,2);

ALTER TABLE INVENTORY_TX ADD COLUMN UI_ITEM_AMOUNT NUMERIC(10,2);

ALTER TABLE INVENTORY_TX ADD COLUMN UI_ITEM_DISCOUNT NUMERIC(10,2);

ALTER TABLE INVENTORY_TX ADD COLUMN UI_WEIGHT_DISCOUNT NUMERIC(10,2);

ALTER TABLE INVENTORY_TX ADD COLUMN UI_TOTAL_AMOUNT NUMERIC(10,2);
