

CREATE TABLE ITEM_CATEGORY
(
    ITEM_CATEGORY_ID     INTEGER NOT NULL PRIMARY KEY,
    CATEGORY_NAME        TEXT UNIQUE,
    PARENT_ID            INTEGER,
    ITEM_COUNT           INTEGER NOT NULL,
            
    CREATE_DATE CHAR(19) NOT NULL,
    MODIFY_DATE CHAR(19) NOT NULL,
    
    FOREIGN KEY(PARENT_ID) REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_ID)    
);


ALTER TABLE ITEM ADD COLUMN ITEM_CATEGORY INTEGER;

ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_CATEGORY) REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_ID);



ALTER TABLE ITEM ADD COLUMN PRICE_CATEGORY INTEGER; /* 1=Step, 2=Tier, 3=Liner */

ALTER TABLE ITEM ADD COLUMN ITEM_LINEAR NUMERIC(10,4); /* for PRICE_CATEGORY = 3 */

CREATE TABLE ITEM_PRICE
(
    ITEM_PRICE_ID        INTEGER NOT NULL PRIMARY KEY,
    ITEM_ID              INTEGER NOT NULL,
    TO_QTY               NUMERIC(10,4) NOT NULL,    
    FROM_QTY             NUMERIC(10,4) NOT NULL,
    UNIT_PRICE           NUMERIC(10,4) NOT NULL,
    
    CREATE_DATE          CHAR(19) NOT NULL,
    MODIFY_DATE          CHAR(19) NOT NULL,
    
    FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID)    
);
