
CREATE TABLE ACCOUNT_DOC_DEPOSIT
(
    ACT_DOC_DEPOSIT_ID              INTEGER NOT NULL PRIMARY KEY,
    ACCOUNT_DOC_ID                  INTEGER NOT NULL,
    RATIO_TYPE                      INTEGER NOT NULL, /* 1=Percent, 2=Fix */
    AMOUNT_PCT                      NUMERIC(12, 2) NOT NULL,
    DEPOSIT_AMOUNT                  NUMERIC(12, 2) NOT NULL,    
    NOTE                            TEXT,

    CREATE_DATE CHAR(19)            NOT NULL,
    MODIFY_DATE CHAR(19)            NOT NULL,

    FOREIGN KEY(ACCOUNT_DOC_ID) REFERENCES ACCOUNT_DOC(ACCOUNT_DOC_ID)
);

CREATE SEQUENCE ACCOUNT_DOC_DEPOSIT_SEQ START 1;

ALTER TABLE ACCOUNT_DOC ADD REF_DOCUMENT_DATE CHAR(19);

ALTER TABLE ACCOUNT_DOC ADD REF_QUOTATION_NO TEXT;

/* Only receipt will be using this */
ALTER TABLE ACCOUNT_DOC_ITEM ADD REF_DOC_ID INTEGER;
ALTER TABLE ACCOUNT_DOC_ITEM ADD FOREIGN KEY(REF_DOC_ID) REFERENCES ACCOUNT_DOC(ACCOUNT_DOC_ID);

ALTER TABLE ACCOUNT_DOC ADD VAT_MONTH_YEAR CHAR(19);
ALTER TABLE ACCOUNT_DOC ADD WH_MONTH_YEAR CHAR(19);

UPDATE ACCOUNT_DOC SET VAT_MONTH_YEAR = DOCUMENT_DATE;
UPDATE ACCOUNT_DOC SET WH_MONTH_YEAR = DOCUMENT_DATE;

ALTER TABLE ACCOUNT_DOC ADD INTERNAL_DRCR_FLAG CHAR(1);
UPDATE ACCOUNT_DOC SET INTERNAL_DRCR_FLAG = 'N' WHERE DOCUMENT_NO LIKE '(%)%';
/* Correct the above one */
UPDATE ACCOUNT_DOC SET INTERNAL_DRCR_FLAG = 'Y' WHERE DOCUMENT_NO LIKE '(%)%'; 

/* Correct one more time */
UPDATE ACCOUNT_DOC SET INTERNAL_DRCR_FLAG = 'N';
UPDATE ACCOUNT_DOC SET INTERNAL_DRCR_FLAG = 'Y' WHERE DOCUMENT_NO LIKE '(%)%'; 

ALTER TABLE ACCOUNT_DOC ADD REF_QUOTATION_ID INTEGER;
ALTER TABLE ACCOUNT_DOC ADD FOREIGN KEY(REF_QUOTATION_ID) REFERENCES AUXILARY_DOC(AUXILARY_DOC_ID);

ALTER TABLE AUXILARY_DOC ADD IN_USED_BY_SO CHAR(1);
UPDATE AUXILARY_DOC SET IN_USED_BY_SO = 'N';


ALTER TABLE ACCOUNT_DOC ADD REF_SALE_ORDER_ID INTEGER;
ALTER TABLE ACCOUNT_DOC ADD FOREIGN KEY(REF_SALE_ORDER_ID) REFERENCES ACCOUNT_DOC(ACCOUNT_DOC_ID);

ALTER TABLE ACCOUNT_DOC ADD REF_SALE_ORDER_NO TEXT;

ALTER TABLE ACCOUNT_DOC ADD SO_IN_USED_BY_INVOICE CHAR(1);
UPDATE ACCOUNT_DOC SET SO_IN_USED_BY_INVOICE = 'N';

ALTER TABLE ACCOUNT_DOC ADD INDEX_PAYMENT TEXT;

ALTER TABLE ACCOUNT_DOC ADD IS_APPROVED_DOC_NO CHAR(1);
UPDATE ACCOUNT_DOC SET IS_APPROVED_DOC_NO = 'N';

INSERT INTO GLOBAL_VARIABLE
(GLOBAL_VARIABLE_ID, VARIABLE_NAME, VARIABLE_TYPE, VARIABLE_CATEGORY, VARIABLE_VALUE, VARIABLE_DESC, CREATE_DATE, MODIFY_DATE)
VALUES
(22, 'APPROVED_DOC_NUMBER_STRING', 2, 1, 'Y', 'Bit 0=Sale Invoice', '2018/06/09 00:00:00', '2018/06/09 00:00:00');

ALTER TABLE ACCOUNT_DOC ADD BILL_SUMMARY_ID INTEGER;
ALTER TABLE ACCOUNT_DOC ADD FOREIGN KEY(BILL_SUMMARY_ID) REFERENCES ACCOUNT_DOC(ACCOUNT_DOC_ID);

ALTER TABLE ACCOUNT_DOC_ITEM ADD PO_ID INTEGER;
ALTER TABLE ACCOUNT_DOC_ITEM ADD FOREIGN KEY(PO_ID) REFERENCES ACCOUNT_DOC(ACCOUNT_DOC_ID);

ALTER TABLE ACCOUNT_DOC_ITEM DROP CONSTRAINT account_doc_item_po_id_fkey;
ALTER TABLE ACCOUNT_DOC_ITEM ADD FOREIGN KEY(PO_ID) REFERENCES AUXILARY_DOC(AUXILARY_DOC_ID);

ALTER TABLE ACCOUNT_DOC ADD INDEX_PROJECT TEXT;

ALTER TABLE PACKAGE_PRICE ADD SERVICE_TYPE INTEGER;

ALTER TABLE AUXILARY_DOC ADD QUOTATION_TYPE INTEGER;
UPDATE AUXILARY_DOC SET QUOTATION_TYPE = 1;

ALTER TABLE AUXILARY_DOC_ITEM ADD ITEM_DETAIL TEXT;


ALTER TABLE ACCOUNT_DOC ADD NOTE TEXT;

ALTER TABLE ACCOUNT_DOC_ITEM ADD ITEM_DETAIL TEXT;

ALTER TABLE ACCOUNT_DOC_PAYMENT ADD COLUMN FEE_AMOUNT NUMERIC(12, 2);

ALTER TABLE ACCOUNT_DOC ADD COLUMN DOCUMENT_YYYYMM CHAR(6);
ALTER TABLE ACCOUNT_DOC ADD COLUMN DOCUMENT_YYYY CHAR(4);

UPDATE ACCOUNT_DOC SET DOCUMENT_YYYYMM = substring(DOCUMENT_DATE from 1 for 4) || substring(DOCUMENT_DATE from 6 for 2);
UPDATE ACCOUNT_DOC SET DOCUMENT_YYYY = substring(DOCUMENT_DATE from 1 for 4);

ALTER TABLE ENTITY ADD COLUMN CONTACT_PERSON TEXT;

ALTER TABLE AUXILARY_DOC ADD COLUMN CONTACT_PERSON TEXT;
ALTER TABLE AUXILARY_DOC ADD COLUMN REVISE_NO TEXT;

UPDATE ACCOUNT_DOC SET DOCUMENT_YYYYMM = substring(DOCUMENT_DATE from 1 for 4) || substring(DOCUMENT_DATE from 6 for 2);
UPDATE ACCOUNT_DOC SET DOCUMENT_YYYY = substring(DOCUMENT_DATE from 1 for 4);

ALTER TABLE PROJECT ADD COLUMN PRODUCT TEXT;
ALTER TABLE PROJECT ADD COLUMN CBU TEXT;
ALTER TABLE PROJECT ADD COLUMN SYSTEM TEXT;

ALTER TABLE ITEM ADD COLUMN BORROW_FLAG CHAR(1);
ALTER TABLE LOCATION ADD COLUMN BORROW_FLAG CHAR(1);

UPDATE ITEM SET BORROW_FLAG = 'N';
UPDATE LOCATION SET BORROW_FLAG = 'N';

ALTER TABLE INVENTORY_TX ADD COLUMN PROJECT_ID INTEGER;
ALTER TABLE INVENTORY_TX ADD FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(PROJECT_ID);

ALTER TABLE INVENTORY_DOC ADD INTERNAL_DOC_FLAG CHAR(1);

ALTER TABLE ACCOUNT_DOC ADD REVENUE_EXPENSE_FOR_WH_AMT NUMERIC(12, 2);
ALTER TABLE ACCOUNT_DOC ADD REVENUE_EXPENSE_FOR_VAT_AMT NUMERIC(12, 2);

UPDATE ACCOUNT_DOC AD SET REVENUE_EXPENSE_FOR_WH_AMT = (
    SELECT SUM(REVENUE_EXPENSE_AMT) FROM ACCOUNT_DOC_ITEM ADI 
    WHERE (ADI.ACCOUNT_DOC_ID = AD.ACCOUNT_DOC_ID) AND (ADI.WH_TAX_FLAG = 'Y')
);

UPDATE ACCOUNT_DOC AD SET REVENUE_EXPENSE_FOR_VAT_AMT = (
    SELECT SUM(REVENUE_EXPENSE_AMT) FROM ACCOUNT_DOC_ITEM ADI 
    WHERE (ADI.ACCOUNT_DOC_ID = AD.ACCOUNT_DOC_ID) AND (ADI.VAT_TAX_FLAG = 'Y')
);

ALTER TABLE ACCOUNT_DOC_RECEIPT ADD REVENUE_EXPENSE_FOR_WH_AMT NUMERIC(12, 2);
ALTER TABLE ACCOUNT_DOC_RECEIPT ADD REVENUE_EXPENSE_FOR_VAT_AMT NUMERIC(12, 2);

ALTER TABLE INVENTORY_DOC ADD RETURN_DUE_DATE CHAR(9);
ALTER TABLE INVENTORY_DOC DROP COLUMN RETURN_DUE_DATE;
ALTER TABLE INVENTORY_DOC ADD RETURN_DUE_DATE CHAR(19);

ALTER TABLE INVENTORY_TX ADD LOT_FLAG CHAR(1);
UPDATE INVENTORY_TX SET LOT_FLAG = 'N';

ALTER TABLE INVENTORY_TX ADD RETURNED_QUANTITY NUMERIC(12, 2);
ALTER TABLE INVENTORY_TX ADD RETURNED_ALL_FLAG CHAR(1);

UPDATE INVENTORY_TX SET RETURNED_ALL_FLAG = 'N';

ALTER TABLE INVENTORY_TX ADD RETURNED_QUANTITY_NEED NUMERIC(12, 2);

ALTER TABLE INVENTORY_TX ADD BORROW_ID INTEGER;
ALTER TABLE INVENTORY_TX ADD FOREIGN KEY(BORROW_ID) REFERENCES INVENTORY_TX(TX_ID);

ALTER TABLE INVENTORY_TX ADD BORROW_DOCUMENT_NO TEXT;

ALTER TABLE ACCOUNT_DOC ADD VAT_CLAIMABLE CHAR(1);
UPDATE ACCOUNT_DOC SET VAT_CLAIMABLE = 'Y';
