
CREATE TABLE PAYROLL_ALLOWANCE_ITEM
(
    PAYROLL_ALLOWANCE_ITEM_ID         INTEGER NOT NULL PRIMARY KEY,
    OT_DOC_ID                         INTEGER NOT NULL,
    ALLOWANCE_TYPE                    INTEGER NOT NULL,    
    ALLOWANCE_AMOUNT                  NUMERIC(12, 2),
    ALLOWANCE_NOTE                    TEXT,
    ALLOWANCE_DATE                    CHAR(19) NOT NULL,
    ALLOWANCE_QUANTITY                NUMERIC(12, 2),
    ALLOWANCE_PRICE                   NUMERIC(12, 2),

    CREATE_DATE                     CHAR(19) NOT NULL,
    MODIFY_DATE                     CHAR(19) NOT NULL,

    FOREIGN KEY(OT_DOC_ID) REFERENCES OT_DOCUMENT(OT_DOC_ID)
);

CREATE SEQUENCE PAYROLL_ALLOWANCE_ITEM_SEQ START 1;
