ALTER TABLE EMPLOYEE ADD FEE_VEHICLE NUMERIC(12, 2);

ALTER TABLE OT_DOC_ITEM ADD ACTUAL_LEAVE_DEDUCT_FLAG CHAR(1);
UPDATE OT_DOC_ITEM SET ACTUAL_LEAVE_DEDUCT_FLAG = 'Y';

ALTER TABLE OT_DOC_ITEM ADD DEDUCT_PENALTY_PENDING NUMERIC(12, 2);
