ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_1 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_1 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_1 NUMERIC(12, 2);

ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_1 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_1 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_1 NUMERIC(12, 2);

ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_2 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_2 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_2 NUMERIC(12, 2);

ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_3 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_3 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_3 NUMERIC(12, 2);

ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_4 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_4 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_4 NUMERIC(12, 2);

ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_5 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_5 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_5 NUMERIC(12, 2);

ALTER TABLE OT_DOCUMENT ADD DEDUCTION_MINUTE_TOTAL_6 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_AMOUNT_6 NUMERIC(12, 2);
ALTER TABLE OT_DOCUMENT ADD DEDUCTION_HOUR_ROUNDED_TOTAL_6 NUMERIC(12, 2);
