ALTER TABLE PAYROLL_DOC_ITEM ADD ACTUAL_LEAVE_DEDUCT_FLAG CHAR(1);
ALTER TABLE PAYROLL_DOC_ITEM ADD DEDUCT_PENALTY_PENDING NUMERIC(12, 2);

UPDATE PAYROLL_DOC_ITEM SET ACTUAL_LEAVE_DEDUCT_FLAG = 'Y';
