
CREATE TABLE PAYROLL_DOCUMENT
(
    PAYROLL_DOC_ID                  INTEGER NOT NULL PRIMARY KEY,
    DOCUMENT_DATE                   CHAR(19) NOT NULL,
    PAYROLL_YEAR                    TEXT NOT NULL,
    PAYROLL_MONTH                   TEXT NOT NULL,
    EMPLOYEE_TYPE                   INTEGER NOT NULL, /* 1=Daily, 2=Monthly */
    DOCUMENT_STATUS                 INTEGER NOT NULL,
    NOTE                            TEXT,    
    RECEIVE_AMOUNT                  NUMERIC(12, 2),
    DEDUCT_AMOUNT                   NUMERIC(12, 2),
    REMAIN_AMOUNT                   NUMERIC(12, 2),
    ITEM_COUNT                      NUMERIC(12, 2),

    CREATE_DATE CHAR(19)            NOT NULL,
    MODIFY_DATE CHAR(19)            NOT NULL
);

CREATE SEQUENCE PAYROLL_DOCUMENT_SEQ START 1;

CREATE TABLE PAYROLL_DOC_ITEM
(
    PAYROLL_DOC_ITEM_ID             INTEGER NOT NULL PRIMARY KEY,
    PAYROLL_DOC_ID                  INTEGER NOT NULL,
    EMPLOYEE_ID                     INTEGER NOT NULL,
    NOTE                            TEXT,
    RECEIVE_AMOUNT                  NUMERIC(12, 2),
    DEDUCT_AMOUNT                   NUMERIC(12, 2),
    REMAIN_AMOUNT                   NUMERIC(12, 2),

    RECEIVE_INCOME                  NUMERIC(12, 2),
    RECEIVE_OT                      NUMERIC(12, 2),
    RECEIVE_POSITION                NUMERIC(12, 2),
    RECEIVE_TRANSPORTATION          NUMERIC(12, 2),
    RECEIVE_TELEPHONE               NUMERIC(12, 2),
    RECEIVE_COMMISSION              NUMERIC(12, 2),
    RECEIVE_ALLOWANCE               NUMERIC(12, 2),
    RECEIVE_BONUS                   NUMERIC(12, 2),
    RECEIVE_REFUND                  NUMERIC(12, 2),
    DEDUCT_TAX                      NUMERIC(12, 2),
    DEDUCT_PENALTY                  NUMERIC(12, 2),
    DEDUCT_BORROW                   NUMERIC(12, 2),
    DEDUCT_ADVANCE                  NUMERIC(12, 2),
    DEDUCT_SOCIAL_SECURITY          NUMERIC(12, 2),
    DEDUCT_OTHER                    NUMERIC(12, 2),
    DEDUCT_OTHER_NOTE               NUMERIC(12, 2),

    CREATE_DATE CHAR(19)            NOT NULL,
    MODIFY_DATE CHAR(19)            NOT NULL,

    FOREIGN KEY(PAYROLL_DOC_ID) REFERENCES PAYROLL_DOCUMENT(PAYROLL_DOC_ID),
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE SEQUENCE PAYROLL_DOC_ITEM_SEQ START 1;

ALTER TABLE PAYROLL_DOC_ITEM DROP COLUMN DEDUCT_OTHER_NOTE;

ALTER TABLE PAYROLL_DOC_ITEM ADD SOCIAL_SECURITY_COMPANY NUMERIC(12, 2);

ALTER TABLE PAYROLL_DOC_ITEM ADD DEDUCT_COVERAGE NUMERIC(12, 2);

ALTER TABLE PAYROLL_DOC_ITEM ADD RECEIVE_OTHERS_TOTAL NUMERIC(12, 2);

UPDATE PAYROLL_DOC_ITEM SET RECEIVE_OTHERS_TOTAL = RECEIVE_COMMISSION + RECEIVE_ALLOWANCE + RECEIVE_BONUS;

ALTER TABLE PAYROLL_DOC_ITEM ADD GRAND_TOTAL_AMOUNT NUMERIC(12, 2);

ALTER TABLE PAYROLL_DOCUMENT ADD FROM_SALARY_DATE CHAR(19);
ALTER TABLE PAYROLL_DOCUMENT ADD TO_SALARY_DATE CHAR(19);

ALTER TABLE EMPLOYEE ADD COLUMN BANK_ID INTEGER;
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (BANK_ID) REFERENCES MASTER_REF(MASTER_ID);

ALTER TABLE EMPLOYEE ADD COLUMN ACCOUNT_NO TEXT;
ALTER TABLE EMPLOYEE ADD COLUMN BANK_BRANCH_NAME TEXT;

ALTER TABLE EMPLOYEE ADD COLUMN ID_NUMBER TEXT;

ALTER TABLE PAYROLL_DOC_ITEM ADD BAL_TOTAL_DEFINITION TEXT;
ALTER TABLE PAYROLL_DOC_ITEM ADD BAL_YEAR_DEFINITION TEXT;
ALTER TABLE PAYROLL_DOC_ITEM ADD ENDING_TOTAL_DEFINITION TEXT;
ALTER TABLE PAYROLL_DOC_ITEM ADD ENDING_YEAR_DEFINITION TEXT;

ALTER TABLE EMPLOYEE ADD COLUMN HOUR_RATE NUMERIC(12, 2);
