
CREATE TABLE VIRTUAL_DIRECTORY
(
    DIRECTORY_ID                    INTEGER NOT NULL PRIMARY KEY,
    DIRECTORY_NAME                  TEXT NOT NULL,
    DIRECTORY_DESCRIPTION           TEXT,
    PARENT_DIRECTORY_ID             INTEGER,
    CATEGORY                        INTEGER NOT NULL, /* 1=department, 2=position */

    CREATE_DATE CHAR(19)            NOT NULL,
    MODIFY_DATE CHAR(19)            NOT NULL,

    FOREIGN KEY(PARENT_DIRECTORY_ID) REFERENCES VIRTUAL_DIRECTORY(DIRECTORY_ID)
);

CREATE SEQUENCE VIRTUAL_DIRECTORY_SEQ START 1;

ALTER TABLE COMPANY_PROFILE ADD REGISTRATION_NAME TEXT;
ALTER TABLE COMPANY_PROFILE ADD REGISTRATION_ADDRESS TEXT;
ALTER TABLE COMPANY_PROFILE ADD BUILDING_NAME TEXT;
ALTER TABLE COMPANY_PROFILE ADD ROOM_NO TEXT;
ALTER TABLE COMPANY_PROFILE ADD FLOOR_NO TEXT;
ALTER TABLE COMPANY_PROFILE ADD VILLAGE_NAME TEXT;
ALTER TABLE COMPANY_PROFILE ADD HOME_NO TEXT;
ALTER TABLE COMPANY_PROFILE ADD MOO TEXT;
ALTER TABLE COMPANY_PROFILE ADD SOI TEXT;
ALTER TABLE COMPANY_PROFILE ADD ROAD TEXT;
ALTER TABLE COMPANY_PROFILE ADD DISTRICT TEXT;
ALTER TABLE COMPANY_PROFILE ADD TOWN TEXT;
ALTER TABLE COMPANY_PROFILE ADD PROVINCE TEXT;
ALTER TABLE COMPANY_PROFILE ADD ZIP TEXT;

UPDATE GLOBAL_VARIABLE SET VARIABLE_DESC = 'Bit 0=Sale Invoice, 1=Sale Receipt' WHERE VARIABLE_NAME = 'APPROVED_DOC_NUMBER_STRING';


CREATE TABLE TAX_DOCUMENT
(
    TAX_DOC_ID                      INTEGER NOT NULL PRIMARY KEY,
    TAX_YEAR                        TEXT NOT NULL,
    TAX_MONTH                       TEXT NOT NULL,
    DOCUMENT_TYPE                   INTEGER NOT NULL, /* 1=PP30, 2=REV3, 3=REV53 */
    DOCUMENT_STATUS                 INTEGER NOT NULL,
    NOTE                            TEXT,

    CREATE_DATE CHAR(19)            NOT NULL,
    MODIFY_DATE CHAR(19)            NOT NULL
);

CREATE SEQUENCE TAX_DOCUMENT_SEQ START 1;

ALTER TABLE TAX_DOCUMENT ADD DOCUMENT_DATE CHAR(19) NOT NULL;

CREATE TABLE TAX_DOCUMENT_PP30
(
    TAX_PP30_ID                     INTEGER NOT NULL PRIMARY KEY,
    TAX_DOC_ID                      INTEGER NOT NULL,

    SALE_AMOUNT                     NUMERIC(12, 2),
    SALE_ZERO_PCT_AMOUNT            NUMERIC(12, 2),
    SALE_EXEMPT_AMOUNT              NUMERIC(12, 2),
    SALE_ELIGIBLE_AMOUNT            NUMERIC(12, 2),
    SALE_VAT_AMOUNT                 NUMERIC(12, 2),
    PURCHASE_ELIGIBLE_AMOUNT        NUMERIC(12, 2),
    PURCHASE_VAT_AMOUNT             NUMERIC(12, 2),
    VAT_EXTRA_AMOUNT                NUMERIC(12, 2),
    VAT_CLAIM_AMOUNT                NUMERIC(12, 2),
    VAT_PREV_FWD_AMOUNT             NUMERIC(12, 2),
    VAT_EXTRA_TOTAL_AMOUNT          NUMERIC(12, 2),
    VAT_CLAIM_TOTAL_AMOUNT          NUMERIC(12, 2),
    VAT_EXTRA_GRAND_AMOUNT          NUMERIC(12, 2),
    VAT_CLAIM_GRAND_AMOUNT          NUMERIC(12, 2),
    ADDITIONAL_AMOUNT               NUMERIC(12, 2),
    PENALTY_AMOUNT                  NUMERIC(12, 2),

    CREATE_DATE                     CHAR(19) NOT NULL,
    MODIFY_DATE                     CHAR(19) NOT NULL,

    FOREIGN KEY(TAX_DOC_ID) REFERENCES TAX_DOCUMENT(TAX_DOC_ID)
);

CREATE SEQUENCE TAX_DOCUMENT_PP30_SEQ START 1;

INSERT INTO GLOBAL_VARIABLE
(GLOBAL_VARIABLE_ID, VARIABLE_NAME, VARIABLE_TYPE, VARIABLE_CATEGORY, VARIABLE_VALUE, VARIABLE_DESC, CREATE_DATE, MODIFY_DATE)
VALUES
(25, 'REVENUE_DEP_SUPPLIER_CODE', 2, 1, 'REV-TAX-001', 'Supplier code for Revenue Department', '2019/01/08 00:00:00', '2019/01/08 00:00:00');

ALTER TABLE TAX_DOCUMENT ADD CHEQUE_ID INTEGER;
ALTER TABLE TAX_DOCUMENT ADD FOREIGN KEY(CHEQUE_ID) REFERENCES CHEQUE(CHEQUE_ID);

CREATE TABLE TAX_DOCUMENT_REV3_53
(
    TAX_RV3_53_ID                   INTEGER NOT NULL PRIMARY KEY,
    TAX_DOC_ID                      INTEGER NOT NULL,

    ACCOUNT_DOC_ID                  INTEGER NOT NULL,
    ACCOUNT_DOC_ITEM_ID             INTEGER NOT NULL,
    DOCUMENT_TYPE                   INTEGER NOT NULL,
    RECEIPT_DATE                    CHAR(19) NOT NULL,
    WH_NO                           TEXT NOT NULL,
    INVOICE_NO                      TEXT NOT NULL,
    INVOICE_DATE                    CHAR(19) NOT NULL,
    DOCUMENT_NO                     TEXT NOT NULL,
    DOCUMENT_DATE                   CHAR(19) NOT NULL,
    SUPPLIER_NAME                   TEXT NOT NULL,
    SUPPLIER_ADDRESS                TEXT NOT NULL,
    SUPPLIER_ID                     INTEGER NOT NULL,
    SUPPLIER_TAX_ID                 TEXT NOT NULL, 
    EXPENSE_REVENUE_AMT             NUMERIC(12, 2),
    WH_GROUP                        INTEGER,
    WH_PAY_TYPE                     INTEGER,
    SUPPLIER_REV_TYPE               INTEGER,
    WH_PCT                          NUMERIC(12, 2),
    WH_AMOUNT                       NUMERIC(12, 2),

    CREATE_DATE                     CHAR(19) NOT NULL,
    MODIFY_DATE                     CHAR(19) NOT NULL,

    FOREIGN KEY(TAX_DOC_ID) REFERENCES TAX_DOCUMENT(TAX_DOC_ID)
);

CREATE SEQUENCE TAX_DOCUMENT_REV3_53_SEQ START 1;

ALTER TABLE TAX_DOCUMENT ADD WH_AMOUNT NUMERIC(12, 2);
ALTER TABLE TAX_DOCUMENT ADD EXPENSE_REVENUE_AMT NUMERIC(12, 2);

ALTER TABLE TAX_DOCUMENT ADD ITEM_COUNT INTEGER;

ALTER TABLE TAX_DOCUMENT ADD PREVIOUS_RUN_YEAR INTEGER;
ALTER TABLE TAX_DOCUMENT ADD PREVIOUS_RUN_MONTH INTEGER;

ALTER TABLE SERVICE ADD IS_SALARY CHAR(1);
UPDATE SERVICE SET IS_SALARY = 'N';

ALTER TABLE ACCOUNT_DOC_ITEM ADD FACTOR INTEGER;

UPDATE ACCOUNT_DOC_ITEM SET FACTOR = 1;
UPDATE ACCOUNT_DOC_ITEM SET FACTOR = -1 WHERE ACCOUNT_DOC_ID IN 
(
    SELECT ACCOUNT_DOC_ID FROM ACCOUNT_DOC WHERE ((DOCUMENT_TYPE = '3') OR (DOCUMENT_TYPE = '7'))
);

ALTER TABLE ACCOUNT_DOC ADD DRCR_FOR_EXPENSE_REVENUE CHAR(1);
UPDATE ACCOUNT_DOC SET DRCR_FOR_EXPENSE_REVENUE = 'Y';
